### ISSUE TITLE
Optimize session lookup

### ISSUE THREAD

**Issue by olavmrk** [Uninett/mod_auth_mellon#1]
By adjusting storing the index in the session table as part of the session 
id, we could find a session immediately without scanning the session table 
for a matching session id

**Comment by bdauvergne** [comment]
Is performance really hurting on this point ?

**Comment by olavmrk** [comment]
No, where we use it at least. This is mostly an idea that I just noted down.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
