### ISSUE TITLE
Mellon + public resource

### ISSUE THREAD

**Issue by jsirex** [UNINETT/mod_auth_mellon#100]
I need to make public location. Here is config i wrote:
```apache
...
<Location /public>
    # Do not require auth
    Allow from all
    Satisfy any
</Location>

<Location />
    MellonEnable "auth"
    # Other Mellon* directives
   Require valid-user # after upgrading apache2 this doesn't fail server anymore
</Location>
```

I always get 401 error code. I also tried:
* require all granted (getting 303 and mellon login
* mellonenable off (303
* mellonenable info (303)
* AuthType none (303)

Nothing helps: I always receive 401 error code.

Looks like a bug.

**Comment by olavmrk** [comment]
This looks like a configuration error in your setup. Try something like this in `<Location /public>`:

```
MellonEnable off
Require all granted
```

Alternatively drop the `Require valid-user` in `<Location />` -- `MellonEnable "auth"` will still enforce authentication.
