### ISSUE TITLE
Can I share authentication between virtual hosts?

### ISSUE THREAD

**Issue by andreaslang** [UNINETT/mod_auth_mellon#102]
I have a setup with name base virtual hosts e.g.

main.domain.com
app1.main.domain.com

main.domain.com is registered with the IdP including the ACS https://main.domain.com/mellon/postResponse

Ideally, I would define globally for apache with the Location tag mod mellon authentication and once I logged in at main.domain.com I would not be redirected to the IdP again. This does not seem to be the case though. It looks to me every Virtual Host has its own mellon context. Therefore going to app1.main.domain.com I will be redirected again (MellonRedirectDomains is configured) to the IdP. Worse, as the IdP posts the response to main.domain.com I cannot authenticate successfully for app1.main.domain.com, it will just go into a redirect loop.

Is there any way to set this up properly?

My config looks like this (simplified)

sso.conf:
```
<IfModule auth_mellon_module>
  <Location />
    MellonEnable "auth"

    # SP config
    MellonSPPrivateKeyFile /path/to/key
    MellonSPCertFile /path/to/cert
    MellonSPMetadataFile /path/to/meta

    # IdP config
    MellonIdPMetadataFile /path/to/idp-meta

    MellonUser "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"

    # The location all endpoints should be located under.
    MellonEndpointPath /mellon

    MellonRedirectDomains main.domain.com app1.domain.com

  </Location>

  <Location /mellon>
    MellonEnable "info"
  </Location>
</IfModule>
```

Virtual hosts
```
Include sso.conf # global
<VirtualHost *:80>
     ServerName main.domain.com
     # ...
</VirtualHost>

<VirtualHost *:80>
     ServerName app1.main.domain.com
     # ...
</VirtualHost>
```

Edit: changing the SP config does not help as the IdP provider forces me to set the reply URL on their side.

**Comment by andreaslang** [comment]
OK, I did experiment a bit and I was wrong, it is not related to the virtual hosts as I suspected the same happens if I do:

```
<VirtualHost *:80>
     Include sso.conf
     ServerName main.domain.com
     ServerAlias app1.main.domain.com
     #...
</VirtualHost>
```

Is there any way I can get mod mellon to accept the login of the main domain for the sub-domain?

**Comment by olavmrk** [comment]
Hi,

my guess is that your problem is with the two sites ending up with different cookies. Try to add `MellonCookieDomain domain.com` to both sites, followed by deleting the session cookie for both sites (named `mellon-cookie` by default).
