### ISSUE TITLE
Support secure context propagation

### ISSUE THREAD

**Issue by specifice** [UNINETT/mod_auth_mellon#104]
If SSL termination is done by an existing reverse proxy solution (e.g. corporate proxy in place), and Apache only acts as a hosting appserver for mellon, then currently mellon is unaware of the fact it is being accessed from SSL-terminated context and SSO does not work (assertion/response url validation in mellon fails).

Suggestion is) to add configuration option containing name of the header (set by SSL-terminating reverse proxy), which will contain the original protocol name (https). This is pretty much similar to Tomcat secure context propagation via RemoteIpValve - see protocolHeader attribute in https://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/valves/RemoteIpValve.htm

> MellonSecureContextHeader X-Forwarded-Proto

For the config above SSL-terminating reverse proxy would set the X-Forwarded-Proto=https (for SSL-terminated urls) and mellon would respectively handle it and adjust all internally used urls (metadata endpoint urls, assertion consumer service urls) from _http://_ to _https://_.

**Comment by olavmrk** [comment]
Hi,

this should not be necessary. Simply configure the ServerName option in Apache so that Apache knows that it is running behind a proxy terminating SSL.

From the [ServerName documentation](https://httpd.apache.org/docs/2.4/mod/core.html#servername)
> Sometimes, the server runs behind a device that processes SSL, such as a reverse proxy, load balancer or SSL offload appliance. When this is the case, specify the https:// scheme and the port number to which the clients connect in the ServerName directive to make sure that the server generates the correct self-referential URLs.
