### ISSUE TITLE
AuthnRequest signing

### ISSUE THREAD

**Issue by cbhrlulb** [UNINETT/mod_auth_mellon#106]
I'm trying to set up mellon to sign AuthnRequests (required by the IdP).  I've set AuthnRequestsSigned and WantAssertionsSigned to true in the SP metadata file, but this hasn't worked.  Using the Firefox SAML tracer plugin, it shows a Signature in the parameter tab, but in the SAML tab it isn't used.  

Looking through the other issues, #60 suggests that this should be possible for SHA1 (which is fine).

Am I missing any extra necessary config?  Thanks for any help.

**Comment by thijskh** [comment]
If you use the HTTP-Redirect binding, an AuthnRequest signature will indeed be in an URL parameter and not in the XML. So this is expected and I believe that you're configured Mellon correctly and that it does what you want.
