### ISSUE TITLE
How can i get the metadata for the IDP?

### ISSUE THREAD

**Issue by patrickpirzer** [UNINETT/mod_auth_mellon#107]
Hello,
I'm going through the instuctions for generic setup of mod_auth_mellon.
The last point was the execution of the shell mellon_create_metadata.sh, which creates the key-, cert- and xml-files.
Now i shall add the metadata for IdP.
But how do i get that metadata-file called "idp-metadata.xml"?

**Comment by thijskh** [comment]
You get it from your IdP?

**Comment by jdennis** [comment]
You have get it from the IdP. Many IdP's provide a URL from which you can fetch the metadata from, often (but not always) it's the URI of the IdP entity id. Sometimes IdP's will send you their metadata if you ask for it. But in any event this is not a mellon issue, you'll have to research your IdP and learn how they publish their metadata.
