### ISSUE TITLE
apr_table_setn() incorrectly used to set Content-Type response header for PAOS/ECP

### ISSUE THREAD

**Issue by jdennis** [UNINETT/mod_auth_mellon#108]
The wrong Apache call is used to set the Content-Type header for a PAOS response in the ECP SAML flow. The Content-Type returned to the ECP client should be "application/vnd.paos+xml" (e.g. constant MEDIA_TYPE_PAOS). However the Content-Type header returned to the client is "text/html" which breaks the ECP flow.

So even though mellon was doing this:

apr_table_setn(r->headers_out, "Content-Type", MEDIA_TYPE_PAOS);

Apache's response filters reset the value of "Content-Type" to "text/html" because the filters key off the request_rec.content_type field which was not being set. The correct call is to use ap_set_content_type().

For reasons not yet understood apr_table_setn() worked in some versions of Apache, not sure why, but clearly it was not correct.

Pull request will follow soon.

**Comment by olavmrk** [comment]
Fixed by pull request #109.
