### ISSUE TITLE
[Question] Does the license allow to distribute the compiled module?

### ISSUE THREAD

**Issue by mar10** [UNINETT/mod_auth_mellon#110]
We would like to deploy a product together with Apache and some standard modules (mod_proxy, ...).

Would the GPL license allow to deploy an unmodified compiled mod_auth_mellon module as well, without open sourcing all of our source code?

(given that we manage to compile it for Windows ;-)

**Comment by olavmrk** [comment]
Hi,

for mod_auth_mellon you must comply with section 3 of the GPL, which requires you to provide a copy of the source code of mod_auth_mellon (or a written offer to provide the source code).

Assuming that your software is not somehow a derived work of mod_auth_mellon, you will not have to open source your software. I assume that your intention here is to use Apache + mod_proxy + mod_auth_mellon as a proxy in front of your software, in which case I certainly think you are in the clear.

**Comment by mar10** [comment]
Thank you, this is what I hoped to hear.

**Comment by sivaram-blr** [comment]
Guys, I need mod_auth_mellon for windows. Have you compiled it for windows? or have any reference??  Thanks
