### ISSUE TITLE
Error processing authn response

### ISSUE THREAD

**Issue by kochsen** [UNINETT/mod_auth_mellon#112]
I get the following error after authenticating through the IdP. Is there an additional configuration I'm missing for Mellon or does this indicate an issue with the IdP configuration?

 Error processing authn response. Lasso error: [-201] The identifier of a provider is unknown to #LassoServer. To register a provider in a #LassoServer object, you must use the methods lasso_server_add_provider() or lasso_server_add_provider_from_buffer().

**Comment by kochsen** [comment]
The IdP metadata mod_auth_mellon was referencing was incorrect.

**Comment by cfsnyder** [comment]
@kochsen  do you remember what was incorrect about your IdP metadata? I'm getting the same error and any would appreciate any tips you can offer. Thanks!

**Comment by kochsen** [comment]
@cfsnyder my issue was the MellonIdPMetadataFile reference was set to the default. I needed to update it to point to my metadata file. I don't think there was anything wrong with my actual metadata file.

**Comment by cfsnyder** [comment]
Ah ok, my metadata file is referenced correctly and seems to be pulled in fine so I seem to be encountering it for a different reason. Thanks for the quick reply though @kochsen
