### ISSUE TITLE
Web-service call failure and session timout

### ISSUE THREAD

**Issue by ravargs** [UNINETT/mod_auth_mellon#118]
I am having an issue of intermittent webservice call failure. Seems this happens after 60 sec and interestingly occurs only in one of the virtual host and after page refresh again starts works.
Apache version: 2.2.15
mode_mellon: 0.8.0-4

Mellon configuration:

>ProxyPass /auth/admin http://host1.lab.net:9088/admin

>
<Location \/>
MellonSPCertFile /data/apache/mod_mellon/sp.cert
MellonSPPrivateKeyFile /data/apache/mod_mellon/sp.key
MellonSPMetadataFile /data/apache/mod_mellon/sp.xml
MellonIdPMetadataFile /data/apache/mod_mellon/idp.xml
MellonEndpointPath /mellon
MellonSubjectConfirmationDataAddressCheck Off
MellonMergeEnvVars On
MellonPostReplay On
AuthType "Mellon"
MellonEnable "auth"
Require valid-user
MellonVariable "cookie"
MellonSecureCookie On
MellonSessionLength 86400
MellonSamlResponseDump On
MellonUser "NameID"
MellonSetEnv "code" "code"
</Location>

RequestHeader set samlresponse %{MELLON_SAML_RESPONSE}s
RequestHeader set samlsession %{MELLON_SESSION}s
RequestHeader set UserToken %{MELLON_code}e`

**Comment by olavmrk** [comment]
You don't include any information about what you mean with "webservice call failure" nor neither access nor error log from Apache, so there isn't really much to go on here. All we can do is to guess.

My guess is that you either reload / graceful restart your apache webserver periodically, which causes the sessions to be dropped, or that the IdP has a really short `SessionNotOnOrAfter` attribute, which causes the session to expire quickly. The refresh of the page presumably involves a trip via the IdP to establish a new session.

You should be able to view the `SessionNotOnOrAfter` attribute bu looking at the `samlresponse` header, and any reloads / graceful restarts of the web server should show up in the error log. To verify whether you are sent via the IdP when refreshing the page, you can look at the access log -- you should see a response sent to the postResponse or artifactResponse endpoints.

**Comment by ravargs** [comment]
By webservice call failure, I meant the POST submitted to backend application. There is no apache webserver restart happening and pretty much nothing in the apache debug log. I will look for the SessionNotOnOrAfter attribute.

**Comment by ravargs** [comment]
Issue resolved by disabling the  "SessionNotOnOrAfter" attribute on IDP
