### ISSUE TITLE
Support authenticated requests to identity providers

### ISSUE THREAD

**Issue by jokajak** [Uninett/mod_auth_mellon#121]
We have a configuration where all TLS requests must include authentication information (specifically x509 certificate).

It would be nice if mod_auth_mellon could supply credentials to identity providers as part of the TLS request.

**Comment by olavmrk** [comment]
Could you clarify what you mean with "as part of the TLS request"? Normally mod_auth_mellon does not connect directly to the IDP, but leaves that to the browser.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
