### ISSUE TITLE
Configuration error: Syntax error/Cannot read file

### ISSUE THREAD

**Issue by yktoo** [Uninett/mod_auth_mellon#123]
I'm getting a strange error with **mod_auth_mellon** failing to read in configuration files:
```
httpd[10556]: AH00526: Syntax error on line 47 of /etc/httpd/conf.d/jenkins_proxy.conf:
httpd[10556]: MellonSPPrivateKeyFile: Cannot read file /etc/httpd/mellon/gr_jenkins.key
```
This happens with files provided as arguments to `MellonSPPrivateKeyFile`, `MellonSPMetadataFile`, and `MellonSPCertFile`, but, surprisingly enough, not with `MellonIdPMetadataFile`. All the files are readable and seemingly have a correct syntax.

The conf file: [jenkins_proxy.conf.txt](https://github.com/UNINETT/mod_auth_mellon/files/1151979/jenkins_proxy.conf.txt)

I'm using **Apache 2.4.6** and **mod_auth_mellon 0.13.1** (compiled from the source, but the error was the same with the stock 0.11.0) on **CentOS Linux release 7.3.1611 (Core)**.

**Comment by olavmrk** [comment]
The difference between the `MellonSP*` files and the `MellonIdPMetadataFile` is that the latter isn't loaded at startup. My guess is that something is blocking Apache from accessing these files. If the permissions grant Apache access to them, maybe the access is blocked by SELinux?

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
