### ISSUE TITLE
unexpected token near LASSO when launching configure

### ISSUE THREAD

**Issue by sdmdev** [UNINETT/mod_auth_mellon#124]
I tried to use autoconf running this command:
./configure --with-apxs2=/usr/bin/apxs 
how to fix this
./configure: line 3138: syntax error near unexpected token `LASSO,'
and 
./configure: line 3138: `PKG_CHECK_MODULES(LASSO, lasso)'

**Comment by thijskh** [comment]
You need to install `pkg-config`, and `liblasso-dev`, as documented in the README.

**Comment by sdmdev** [comment]
thanks @thijskh, I am getting this now: 'no lasso found'

**Comment by sdmdev** [comment]
what should I run to install liblasso-dev? sorry for the dummy question

**Comment by thijskh** [comment]
Try: `sudo apt install liblasso-dev` when using a Debian or Ubuntu system.

If you ask these basic questions I'm not sure you should be compiling your own. Better use the version of Mod Mellon provided by your distribution. E.g. `apt install libapache2-mod-auth-mellon` and done.

**Comment by sdmdev** [comment]
thanks @thijskh, I compiled it! I might need to make a little change on it thats the reason why I am not using a compiled version
