### ISSUE TITLE
Set a Comparison parameter for RequestedAuthnContext 

### ISSUE THREAD

**Issue by DannyBiker** [Uninett/mod_auth_mellon#125]
Hello,

I would need to set a custom value to the "Comparison" parameter of the RequestedAuthnContext SAML tag. Something that would result in `<samlp:RequestedAuthnContext Comparison="minimum">` for instance.

However that doesn't seem to be supported using mod_auth_mellon; do you confirm it ?
If so, is there any workaround ?

Thank you.

**Comment by olavmrk** [comment]
No, there isn't any code in this module for setting the `Comparison` attribute on the `<RequestedAuthnContext>`-element. Adding it would be possible, but unfortunately I don't have the time to look at this now.

**Comment by DannyBiker** [comment]
Ok, thank you for you answer. :)

**Comment by DannyBiker** [comment]
Ok, thank you for you answer. :)
