### ISSUE TITLE
MellonSPMetadataFile: Cannot read file /etc/apache2/mellon/sp-metadata.xml

### ISSUE THREAD

**Issue by sdmdev** [UNINETT/mod_auth_mellon#126]
I installed mellon on ubuntu 16.04 and Apache 2.4.
When I restart the service with sudo service apache2 restart
I am getting this error: "MellonSPMetadataFile: Cannot read file /etc/apache2/mellon/sp-metadata.xml"
but the file is actually present there and with this permissions:
aeedev@ubuntu:/etc/apache2/mellon$ ls -l sp_metadata.xml 
-rwxrwxrwx 1 root root 826 Aug  1 08:11 sp_metadata.xml

**Comment by olavmrk** [comment]
Hi, here you have a typo; you are using `-` in the configuration, but the file uses `_` .
