### ISSUE TITLE
How to build this module in Windows.

### ISSUE THREAD

**Issue by avinash-k** [UNINETT/mod_auth_mellon#127]
I am using apache server in Windows Environment.
How can I compile mod_auth_mellon to use in Windows Setup?

**Comment by olavmrk** [comment]
Hi,

I have never tried to build this module under Windows, so I honestly don't know what would be required to make that work. One thing to keep in mind is that you don't need only this module; you also need its dependencies, so the first step would be to build them. But I know far to little about Windows software development to be able to tell how one would go about setting up a development environment for building mod_auth_mellon and its dependencies.

**Comment by sivaram-blr** [comment]
avinash-k -  I am also in same situation integrating mod_auth_mellon in windows to implement IBM SAML authentication. Did you get it done in windows? Thanks
