### ISSUE TITLE
lasso_login_accept_sso error handling possibly wrong

### ISSUE THREAD

**Issue by mdutton3** [UNINETT/mod_auth_mellon#128]
The return code from `lasso_login_accept_sso` is compared as `(rc < 0)` instead of `(rc == 0)` but the Lasso documentation states at least one error code that is positive.

Comparison in question:
https://github.com/UNINETT/mod_auth_mellon/blob/dba4bbd8f78634684a072d66077ccd06714987d3/auth_mellon_handler.c#L1845

Lasso documentation:
http://lasso.entrouvert.org/documentation/api-reference/lasso-LassoLogin.html#lasso-login-accept-sso

Example possible error code:
http://lasso.entrouvert.org/documentation/api-reference/lasso-Error-Codes.html#LASSO-LOGIN-ERROR-ASSERTION-REPLAY:CAPS

**Comment by olavmrk** [comment]
Good catch! I have now pushed a commit that fixes this case, as well as changing all other places where we use `rc < 0` for checking error returns from the Lasso library.
