### ISSUE TITLE
LASSO_PROFILE_ERROR_MISSING_REMOTE_PROVIDERID error when attempting a logout

### ISSUE THREAD

**Issue by chrisred24** [UNINETT/mod_auth_mellon#130]
When I try to logout of auth mellon using:
/mellon/logout?ReturnTo=...

I get a 500 error. The following is logged: 
Unable to create logout request. Lasso error: [-408] ProviderID not found

I'm assuming this is probably configuration error on my side, but I have little knowledge of SAML and am not sure where to start debugging?

**Comment by olavmrk** [comment]
I had a look at this error, but I don't see any obvious way to trigger it. As long as the user has a session, the ProviderID is supposed to come from that session, and if the user doesn't have a session, we will not try to send a logout request.

I suggest assembling your configuration and any logs that you can find and trying to post it to the mailing list. Maybe someone else have run into a similar issue before.
