### ISSUE TITLE
MellonUser directive should be case insensitive

### ISSUE THREAD

**Issue by mcgitty** [UNINETT/mod_auth_mellon#131]
In error, the IdP sent an attribute name in all caps "EID", while I asked it to be "eid". The RequestHeader directive seems to handle everything case insensitive, so my application still got the right header. However, the MellonUser directive deemed the IdP assertion incorrect with this error:

`[Wed Aug 16 02:57:17.700896 2017] [auth_mellon:notice] [...] [client ...] Didn't find the attribute "eid" in the attributes which were received from the IdP. Cannot set a user for this request without a valid user attribute.`

Mellon should also handle this check case insensitive like the RequestHeader directive.

**Comment by olavmrk** [comment]
Hi,

I have just committed c291232, which should fix this problem.
