### ISSUE TITLE
WSO2 Integration with Mo_Auth_Mellon fails on LogoutRequest

### ISSUE THREAD

**Issue by luyandasiko** [Uninett/mod_auth_mellon#132]
I will have to apologize if this issue has been raised before I did go through this list of issues. So here is the context:

We have a website that is built with Laravel. The Authentication Layer uses a WSO2 Identity Server instance that is hosted remotely (outside our LAN). We have setup this module with our Laravel-Based project. The Service Provider only facilitate SSO on this website and not others on the application server.

The LOGIN REQUEST takes place successfully, however, I have been struggling to get the LOGOUT REQUEST to pull through (see below issues):

``` php
<a href="/secret/endpoint/logout?ReturnTo=https://www.example.org/logged_out.html">Log out</a>
```

When I add the code shown above on my webpage and click the *logout* link for the first time it just shows me a 500 Internal Server Error that when I browser refresh, my SSO LOGOUT REQUEST is only sent then.

Also looking at the log file I see the following error that does not make sense:

```
User attempted to initiate logout without being loggged in., referer: https://referring.domain.com
Unable to create logout request. Lasso error: [-408] ProviderID not found, referer https://referring.domain.com
```

It is not really clear to me whether the issue lies with the IdP, SP which is our Application Server, or Laravel. I can speculate that chances are the issue is with the underlying techology used to build this module I could be wrong (lasso that is).

Anyone to point me to a right direction on how I can fix this?

**Comment by olavmrk** [comment]
Hi,

could you verify that the "User attempted to initiate logout without being loggged in."-message is logged when you initially clock the "Log out"-link?

In that case, it would indicated that you are not actually logged in. There could be many reasons for this. For example, if you start logout on http, while the authentication cookie is only set with the "secure"-flag.

Another option could be a mixup with the mod_auth_mellon configuration, where you somehow end up with two SPs, one in `/secret/endpoint`, and a different at a different set of URLs.

**Comment by luyandasiko** [comment]
Hi,

Can you please see if you can find context in this question here [satckoverflow](https://stackoverflow.com/questions/46069577/logoutrequest-failing-with-wso2-using-module-auth-mellon). Thanks

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
