### ISSUE TITLE
expose AuthenticatingAuthority

### ISSUE THREAD

**Issue by fkooman** [Uninett/mod_auth_mellon#136]
Would it be possible to expose `AuthenticatingAuthority` as an environment variable so applications can use this information? This useful when an IdP is behind a SAML proxy. The only way to currently find out the IdP entityID is to use your own discovery service. Is there an other way? I guess it would be possible to use `MellonSamlResponseDump`, but that seems overkill.

```
<saml:AuthnStatement AuthnInstant="2017-09-22T09:22:40Z"
                     SessionIndex="65b853fb-0fd1-4f90-b3d8-5f3d19f06f84"
                     >
    <saml:AuthnContext>
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
        <saml:AuthenticatingAuthority>https://www.onegini.me</saml:AuthenticatingAuthority>
    </saml:AuthnContext>
</saml:AuthnStatement>
```

**Comment by olavmrk** [comment]
Hi,

I'm not against adding that information as an environment variable, but I don't have time to look at it now. I therefore leave the issue open as a feature request.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
