### ISSUE TITLE
mod_auth_mellon.so: undefined symbol: am_diag_log_init

### ISSUE THREAD

**Issue by lcutlipmason** [UNINETT/mod_auth_mellon#141]
Compiled the new diagnostics code and attempted to start apache and am getting this error:

httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.modules.d/10-auth_mellon.conf: Cannot load modules/mod_auth_mellon.so into server: /etc/httpd/modules/mod_auth_mellon.so: **undefined symbol: am_diag_log_init**

httpd.service: main process exited, code=exited, status=1/FAILURE

kill: cannot find process ""

httpd.service: control process exited, code=exited status=1

Unregistered Authentication Agent for unix-process:11333:121085696 (system bus name :1.8169, object path /org/freedesktop/PolicyKit1/Authenticix-process:11333:121085696 (system bus name :1.8169, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)

Failed to start The Apache HTTP Server.
-------------------------------

I've built it just fine in the past on the same system, is there something wrong or did I overlook something?

**Comment by nneul** [comment]
Did you run a full clean trying to build that - it sounds like you're missing one of the object files in the code - like it had rebuilt only part of the module after enabling that option. I know I've got a build from several weeks back and it has diagnostics enabled.

Try a full clean, including rerunning autogen. (I'm assuming you built from git sources.)

**Comment by eightbitdino** [comment]
I am experiencing this issue as well on Apache 2.4.6 and RHEL 7.4.  If I build without diagnostics enabled, it works fine. If I enable diagnostics, it refuses to start with the error code "am_diag_log_init".  I am building from the latest git commit and I have blown the machine away and started fresh each time to ensure there are no previous configurations interfering.

If I can provide more detail, please let me know.

**Comment by zoltancsoka** [comment]
I see the same on Centos7 with  Apache 2.4.6.  I have cloned the repository and tried immediately with enabled diagnostic. Following that I have retried multiple times with always a full clean up and I got the same error

**Comment by poljane** [comment]
Getting the same error on Amazon Linux instance with Apache/2.2.34

**Comment by jdennis** [comment]
This problem should be fixed with https://github.com/UNINETT/mod_auth_mellon/pull/146, which was merged. If you pull master you should get the fix.

**Comment by olavmrk** [comment]
Thanks for the update! I am closing this issue now; if someone get the same error with the latest version from master, please reopen it.
