### ISSUE TITLE
Help setting up mellon with Team Site using Azure as LDAP

### ISSUE THREAD

**Issue by arenrostamian** [UNINETT/mod_auth_mellon#143]
Hey guys, 

I've spent the last week searching the internet and any and all resources I could find, on how to set up federated access through Azure, using mellon. Specifically we have a team site server running and I need to set up single sing in access. I have followed every guide out there, and practically have read the entire documentation from top to bottom but nothing I do is working. 

Wanted to see if you guys could help me along? 

Here's where I'm at:
- Mellon is installed on the server. We're running RHEL7. I'm pretty sure its installed but I have yet to be able to verify.
- I have generated all the certs keys and xmls. I have the xml from azure also. 
- I'm confident my issue is in my endpoint assignment but I haven't been able to figure it out. 

Please for the love of god, If someone has ANY Information as to how I can get this set up, I would greatly appreciate it.

**Comment by olavmrk** [comment]
Hi,

support requests like this are better handled at the [mailing list](https://sympa.uninett.no/lists/uninett.no/info/modmellon), though I cannot promise that anyone is familiar enough with the Azure & Team Site to answer.

Also, if you haven't already, I suggest first taking a look at the [user guide](https://github.com/UNINETT/mod_auth_mellon/blob/master/doc/user_guide/mellon_user_guide.adoc). Especially the section about Installing & Configuring Mellon.
