### ISSUE TITLE
Ability to define EndpointPath at higher level than authenticated/controlled paths

### ISSUE THREAD

**Issue by nneul** [UNINETT/mod_auth_mellon#148]
I'd like endpoint path to be top level "/sso", which looks like it requires me to set <Location />

However, I don't want everything at / to be access controlled. I'd like to be able to have say '/auth1/' and '/auth2/' directories be protected, but leave /index.html /favicon.ico, etc. as reachable without triggering any SAML operation. 

What I don't want to have to do is to define two separate SAML apps for /auth1/ and /auth2/. 

Do you have a simple example of something like this?

Below is what I'm currently using (at top level), but I'd really like to have the /sso as is it now, but only have /auth-cgi-bin/ be protected. Note that I do not have access to the iDP, so getting changes to it is a very slow process. (The if/else is to allow preemptive basic auth to bypass SAML at the same paths.)

```

    <Location />
       <If "-n req('Authorization')">
            AuthName "... Active Directory"
            AuthBasicProvider ldap
            AuthType basic
            AuthLDAPMaxSubGroupDepth 0
            AuthLDAPBindAuthoritative off
            AuthLDAPRemoteUserAttribute sAMAccountName
            AuthLDAPInitialBindPattern (.+) $1@.......
            AuthLDAPInitialBindAsUser on
            AuthLDAPSearchAsUser on
            AuthLDAPCompareAsUser on
            AuthLDAPUrl "ldaps://.......com/........,dc=com?sAMAccountName,memberOf?sub"
            LDAPReferrals Off

            require ldap-group CN=........,DC=COM
       </If>
       <Else>
            Require valid-user
            AuthType "Mellon"
            MellonEnable "auth"
            MellonVariable "cookie"
            MellonEndpointPath "/sso"
            MellonDefaultLoginPath "/"
            MellonSubjectConfirmationDataAddressCheck Off
            MellonSessionLength 86400
            MellonSPPrivateKeyFile /local/apache-root/mellon/sp-private-key.pem
            MellonIdPMetadataFile /local/apache-root/mellon/idp-metadata.xml
            MellonDoNotVerifyLogoutSignature https://app.onelogin.com/saml/metadata/7....2
        </Else>
    </Location>

```

**Comment by olavmrk** [comment]
Hi,

you can define all the mod_auth_mellon configuration in the top level, but use `MellonEnable "info"` and no `Require valid-user` nor `AuthType "Mellon"`.

Then add location blocks for resources that you want to be protected:
```
<Location /auth1>
  MellonEnable auth
  Require valid-user
  AuthType "Mellon"
</Location>
```

Those locations will inherit all other mod_auth_mellon configuration from the previous top-level location block.

**Comment by nneul** [comment]
@olavmrk  Thank you. This worked perfectly!
