### ISSUE TITLE
Function am_cache_new  -- auth_mellon_cache.c --  apxs:Error: Command failed with rc=65536 

### ISSUE THREAD

**Issue by Jose-Ma** [UNINETT/mod_auth_mellon#151]
I have a problem compiling the latest version of mod_auth_mellon.
When doing the make, it begins to compile and stops with the following error.

[root@merengue mod_auth_mellon-master]# make
/usr/sbin/apxs -Wc,"-std=c99    -DXMLSEC_CRYPTO=\"openssl\" -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1 -pthread -I/usr/include/libxml2 -I/usr/include/xmlsec1 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -g -O2" -Wl,"-lssl -lcrypto   -llasso   -lcurl   -lglib-2.0  " -Wc,-Wall -Wc,-g -c mod_auth_mellon.c auth_mellon_cache.c auth_mellon_config.c auth_mellon_cookie.c auth_mellon_diagnostics.c auth_mellon_handler.c auth_mellon_util.c auth_mellon_session.c auth_mellon_httpclient.c
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wformat-security -fno-strict-aliasing  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1   -I/usr/include/apr-1  -std=c99    -DXMLSEC_CRYPTO="openssl" -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1 -pthread -I/usr/include/libxml2 -I/usr/include/xmlsec1 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -g -O2 -Wall -g  -c -o mod_auth_mellon.lo mod_auth_mellon.c && touch mod_auth_mellon.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wformat-security -fno-strict-aliasing  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1   -I/usr/include/apr-1  -std=c99    -DXMLSEC_CRYPTO="openssl" -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1 -pthread -I/usr/include/libxml2 -I/usr/include/xmlsec1 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -g -O2 -Wall -g  -c -o auth_mellon_cache.lo auth_mellon_cache.c && touch auth_mellon_cache.slo
auth_mellon_cache.c: En la funciÃ³n âam_cache_newâ:
auth_mellon_cache.c:406: error: expected expression before â)â token
apxs:Error: Command failed with rc=65536
.
make: *** [mod_auth_mellon.la] Error 1

The data of the machine are:
[root@merengue mod_auth_mellon-master]# uname -a
Linux merengue 2.6.32-696.3.1.el6.x86_64 #1 SMP Thu Apr 20 11:30:02 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@merengue mod_auth_mellon-master]# httpd -v
Server version: Apache/2.2.15 (Unix)
Server built:   Jul  7 2017 06:40:45

Thank you
JoseMa

**Comment by olavmrk** [comment]
Hi,

thanks for the bug report. I believe it should be fixed as part of pull request #152. If it isn't, please let me know.
