### ISSUE TITLE
Internal errors when MellonEndpointPath is in a protected Location

### ISSUE THREAD

**Issue by daveagill** [UNINETT/mod_auth_mellon#153]
I am not sure if the following is a bug or just a documentation error.

The main README suggest that a configuration like this should work:

```
<Location />
	AuthType "Mellon"
	Require valid-user
	MellonEnable "auth"

	MellonEndpointPath "/saml"
	
	... other mellon config ...
</Location>
```

After trying this in Apache 2.4 with mellon 0.9 I receive internal server errors which indicate that the valid-user requirement is preventing access to SAML endpoint paths during authentication:
```
[Thu Jan 25 11:35:52.628848 2018] [authz_core:debug] [pid 7:tid 140554171496192] mod_authz_core.c(809): [client 192.168.44.1:27082] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Thu Jan 25 11:35:52.628913 2018] [authz_core:debug] [pid 7:tid 140554171496192] mod_authz_core.c(809): [client 192.168.44.1:27082] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Thu Jan 25 11:35:52.628970 2018] [core:error] [pid 7:tid 140554171496192] [client 192.168.44.1:27082] AH00027: No authentication done but request not allowed without authentication for /saml/login. Authentication not configured?
```

It actually make sense (to me) that the SAML endpoint paths should not require a valid-user because we have not yet established whether the user is valid or not at the time when saml/login is being used.

Interestingly, if I remove these directives it seems to work as we would hope:
```
	AuthType "Mellon"
	Require valid-user
```

Which begs the question - are they even needed for mod_auth_mellon? (The documentation suggests they are).

Everything works fine if we are securing any location _other than_ the SAML endpoints. In this example we leave the SAML endpoint unsecured and only secure the /folder location:
```
<Location />
	MellonEnable "info"
	MellonEndpointPath "/saml"
	... other mellon config ...
</Location>

<Location /folder>
	AuthType "Mellon"
	Require valid-user
	MellonEnable "auth"
</Location>
```

I suspect this is a documentation issue, unless mellon is actually supposed to suppress the effect of require valid-user on the SAML endpoints?
Looking for some confirmation either way.

Thanks.

**Comment by olavmrk** [comment]
Hi,

this is a bug in mod_auth_mellon; I think it was fixed in 0.11.

Regarding the use of `AuthType "Mellon"` with `Require valid-user`, they are not really required by mod_auth_mellon. They can however be a useful safeguard in case there is a mistake in the configuration.

A different workaround for this bug is to add a specific `<Location>`-block that matches the `MellonEndpointPath`, and disabling authentication for that URL. I think something like `Require all granted` would work, but I may be mistaken.
