### ISSUE TITLE
SAML Vulnerabilities 

### ISSUE THREAD

**Issue by bharatak** [UNINETT/mod_auth_mellon#161]
Hi,
Saw a vulnerability note today.  I am curious if auth_mellon is affected with this and if any action is required.  

https://www.kb.cert.org/vuls/id/475445
https://duo.com/blog/duo-finds-saml-vulnerabilities-affecting-multiple-implementations

**Comment by thijskh** [comment]
Please see #160

**Comment by bharatak** [comment]
Thanks a lot @thijskh
