### ISSUE TITLE
mod_auth_mellon and eduGAIN

### ISSUE THREAD

**Issue by TanguiC** [Uninett/mod_auth_mellon#162]
We tried to have an SP using mod_auth_mellon in eduGAIN (eduvpn, see https://github.com/eduvpn/documentation/blob/master/SAML.md). We had to roll back for now.
The XML parsing is too slow for such a high number of IdPs (it took 70 secs or more), which resulted in browsers timing out. Can anything be done about this?

**Comment by fkooman** [comment]
It would be great if the XML parsing speed could be improved! For eduVPN specifically I use my own WAYF where I whitelist IdPs, not all IdPs will get access by default. For the whitelisted IdPs I generate a (minimal) XML file with only the for mod_auth_mellon relevant information in there. I guess it doesn't scale if you really want to give (immediate) access to all IdPs, but it worked for us as an ugly workaround...

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
