### ISSUE TITLE
Yum Doesn't have  latest mod_auth_mellon version

### ISSUE THREAD

**Issue by chyamuna** [UNINETT/mod_auth_mellon#163]
We are using Centos as operation system and Yum as package manager.
We require mod_auth_mellon version 0.13.1 to solve whitelisting returnTo URLs on logout.
Yum doesn't have mod_auth_mellon latest version.It has Version 0.11.0 as the latest.
Could you please help us on this?

**Comment by olavmrk** [comment]
This is something to bring up on the issue tracker of your distro rather than here -- it is up to the distros which versions to ship and how quickly new versions should be distributed.
