### ISSUE TITLE
Is there a max limit for MellonCacheSize?

### ISSUE THREAD

**Issue by lmuhlha** [UNINETT/mod_auth_mellon#169]
Hi,

Just a quick question: Is there a max limit for MellonCacheSize?
Or is it just dependent on what the server can handle?

Thanks!

**Comment by olavmrk** [comment]
mod_auth_mellon itself does not enforce any limit. Depending on the OS mod_auth_mellon is running on, there may be limits to the size of the shared memory segment in use for the sessions.

There is also the practical limit -- if it is too big, looking up and finding sessions can take a significant amount of time. At the moment the code for that isn't optimized at all -- it simply scans the table.
