### ISSUE TITLE
Azure AD SAML Attributes

### ISSUE THREAD

**Issue by baileyscott** [UNINETT/mod_auth_mellon#171]
Folks,

I need some help. My SAML assertsion from Azure AD gives (amongst other things) the following attributes:

```
 <AttributeStatement>
    <Attribute Name="http://schemas.microsoft.com/identity/claims/displayname">
         <AttributeValue>Bailey Scott</AttributeValue>
     </Attribute>
     <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress">
         <AttributeValue>bailey.scott@someaddress.com</AttributeValue>
     </Attribute>
</AttributeStatement>
```

My mellon.conf has:

`RequestHeader set Remote_User %{http://schemas.microsoft.com/identity/claims/displayname}e`

I've also tried:

`MellonSetEnvNoPrefix Remote_User "http://schemas.microsoft.com/identity/claims/displayname"`

.... and various other combinations.

My web page php has:

`var_dump($Remote_User);`

.... which just gives NULL.

I've also tried:

` var_dump($_SERVER);`

....which gives lots of output including the field that I want.

Can anyone point me in the right direction?

Thanks,

Bailey

**Comment by olavmrk** [comment]
Hi,

PHP is not like a shell script; environment variables are not populated directly as script variables when the script starts. (Unless you are using [register globals](http://php.net/manual/en/security.globals.php), which nobody should be using anymore. It was disabled by default in PHP 4.2, released in 2002, and was removed from PHP in version 5.4, which was released in 2012.)

Thus you cannot access the variables without going through `$_SERVER`.
