### ISSUE TITLE
Change header for ajax calls to X-Requested-With

### ISSUE THREAD

**Issue by mlongcr** [Uninett/mod_auth_mellon#174]
The module is looking for 'X-Request-With' header to identify ajax requests. Current versions of Chrome and Firefox both use 'X-Requested-With'. 
Changing line 3661 in auth_mellon_handler.c and recompiling the module to resolves the issue. 
![image](https://user-images.githubusercontent.com/23389391/43010733-d8c14f94-8c06-11e8-989c-86a60ae72dfb.png)

**Comment by olavmrk** [comment]
Thanks! I have fixed this in commit 6358a51.
