### ISSUE TITLE
MellonSignatureMethod 

### ISSUE THREAD

**Issue by Hobbyadmin** [Uninett/mod_auth_mellon#175]
the introduction of the mod_mellon-directive „MellonSignatureMethod“ was a good point, it helped us communicating with our IdP. But now we ran into another problem: we were told to use rsa-sha256 for communication with our IdP, but the answers we receive were signed with rsa-sha1 by our IdP.
Is it possible to add a new directive to use different algorithms so we can configure them different for incoming and outgoing messages? Or to implement (an automatic) fallback to another algorithm?

**Comment by Hobbyadmin** [comment]
SP -> mod_auth_mellon-0.13.1-2.el7_5 (Red Hat Enterprise Linux + Apache 2.4.6 + lasso-2.5.1 + OpenSSL 1.0.2k-fips  26 Jan 2017)

**Comment by olavmrk** [comment]
Hi,

could you clarify the issue you are having? The `MellonSignatureMethod` option only controls the signature method used when sending requests, not when receiving responses. I therefore do not see that the configuration you describe should cause any errors.

**Comment by Hobbyadmin** [comment]
Hi Olav,
thank you for the responce. When the MellonSignatureMethod option only control the sending requests we are looking for the point in the SSL Config from the Server which is currently set to rsa 256 for the incoming messages and this one has to work with rsa sha1. Can you please help us here?

**Comment by olavmrk** [comment]
Hi,

it is still not clear to me what the actual issue is here. Could you describe in more detail what happens, what error you are getting and what should have happened instead?

(SSL configuration is completely separate from SAML 2.0 configuration.)

**Comment by Hobbyadmin** [comment]
Currently we are probably stuck at step 6. 
(6) SP redirects to original resource
https://xxx/mellonEP/postResponse
Bad Request
Your browser sent a request that this server could not understand.
[mellon2github.log.gz](https://github.com/Uninett/mod_auth_mellon/files/2274228/mellon2github.log.gz)

**Comment by Hobbyadmin** [comment]
thank you, i will check this tomorrow.

**Comment by GruttAndy** [comment]
Hi,

I extracted the IdP's public-key from his certificate and added MellonIdpPublicKeyFile as PublicKeyfile and on a second try as PEM-certificate, but neither worked.
I also added the MellonIdPCAFile (as PEMcertificate) with and without intermediate certificates, neither did work. Do I have to use a special sequence (CA, Int1, int2)?

I can find both PublicKeyFile and MellonIdPCAFile in the mellon-diagnostics-log, but we still get this "Bad Request" state on POST /mellonEP/postResponse


-8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- 
  MellonIdPPublicKeyFile (idp_public_key_file):
    pathname: "/etc/httpd/ssl.key/<myserverca>.pubkey"
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuPfcqefUkMNCOKJUmMbO
      0ZJqPh0LBf78Jgv9EvRMYK40f0vanuJ03ZiJXTsB0YDDXGe+pyTLmoyffwhmW69X
      WWsd9gqd43atrJFFlNOSWAy0qMCY4X9JHje0pS9MIQp0CqE7KMeg0Ujh/flEjnxc
      EraVdabJhRD93o8ajAoNel4diMeIp+XT/0nTEtSiJZBxDIndWDZHhW1LGV0qO7Ur
      y3/eYKGTpPSVVFWa5MkfRRHQ4eqSxK38HCzUhZRnAXk+erBj0yBpxIFxK0ypXP2i
      miAqsFYxElLJmf0Xy47SWPtxW+/J0j5fdYYJeehoWoXDsLGHlQ89yUi4fIqy+GrB
      0wIDAQAB
      -----END PUBLIC KEY-----
  MellonIdPCAFile (idp_ca_file):
    pathname: "/etc/httpd/ssl.key/<myserverca>.ca"
      -----BEGIN CERTIFICATE-----
      MIIEPjCCAyagAwIBAgIESlOMKDANBgkqhkiG9w0BAQsFADCBvjELMAkGA1UEBhMC
      VVMxFjAUBgNVBAoTDUVudHJ1c3QsIEluYy4xKDAmBgNVBAsTH1NlZSB3d3cuZW50
      cnVzdC5uZXQvbGVnYWwtdGVybXMxOTA3BgNVBAsTMChjKSAyMDA5IEVudHJ1c3Qs
      IEluYy4gLSBmb3IgYXV0aG9yaXplZCB1c2Ugb25seTEyMDAGA1UEAxMpRW50cnVz
      dCBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzIwHhcNMDkwNzA3MTcy
      NTU0WhcNMzAxMjA3MTc1NTU0WjCBvjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUVu
      dHJ1c3QsIEluYy4xKDAmBgNVBAsTH1NlZSB3d3cuZW50cnVzdC5uZXQvbGVnYWwt
      dGVybXMxOTA3BgNVBAsTMChjKSAyMDA5IEVudHJ1c3QsIEluYy4gLSBmb3IgYXV0
      aG9yaXplZCB1c2Ugb25seTEyMDAGA1UEAxMpRW50cnVzdCBSb290IENlcnRpZmlj
      YXRpb24gQXV0aG9yaXR5IC0gRzIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC6hLZy254Ma+KZ6TABp3bqMriVQRrJ2mFOWHLP/vaCeb9zYQYKpSfYs1/T
      RU4cctZOMvJyig/3gxnQaoCAAEUesMfnmr8SVycco2gvCoe9amsOXmXzHHfV1IWN
      cCG0szLni6LVhjkCsbjSR87kyUnEO6fe+1R9V77w6G7CebI6C1XiUJgWMhNcL3hW
      wcKUs/Ja5CeanyTXxuzQmyWC48zCxEXFjJd6BmsqEZ+pCm5IO2/b1BEZQvePB7/1
      U1+cPvQXLOZprE4yTGJ36rfo5bs0vBmLrpxR57d+tVOxMyLlbc9wPBr64ptntoP0
      jaWvYkxN4FisZDQSA/i2jZRjJKRxAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRqciZ60B7vfec7aVHUbI2fkBJmqzAN
      BgkqhkiG9w0BAQsFAAOCAQEAeZ8dlsa2eT8ijYfThwMEYGprmi5ZiXMRrEPR9RP/
      jTkrwPK9T3CMqS/qF8QLVJ7UG5aYMzyorWKiAHarWWluBh1+xLlEjZivEtRh2woZ
      Rkfz6/djwUAFQKXSt/S1mja/qYh2iARVBCuch38aNzx+LaUa2NSJXsq9rD1s2G2v
      1fN2D807iDginWyTmsQ9v4IbZT+mD12q/OWyFcq1rca8PdCE6OoGcrBNOTJ4vz4R
      nAuknZoh8/CbCzB428Hch0P+vGOaysXCHMnHjf87ElgI5rY97HosTvuDls4MPGmH
      VHOkc8KT/1EQrBVUAdj8BbGJoX90g5pJ19xOe4pIb4tF9g==
      -----END CERTIFICATE-----
  MellonIdPMetadataFile (idp_metadata): 1 items
  [ 0] Metadata
    pathname: "/etc/httpd/conf.d/<myserverca>.xml"
      <?xml version="1.0"?>

      <md:EntityDescriptor      xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"
                        xmlns:saml20="urn:oasis:names:tc:SAML:2.0:assertion"
                        xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
                        xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
                        entityID="<myidpserver>.net">

        <md:IDPSSODescriptor    protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">

        <md:SingleSignOnService Location="https://<myidpserver>.net/sso_cond2fa/SingleSignOnService"
                                Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"/>

        <md:SingleLogoutService Location="https://<myidpserver>.net/portal/logout_confirm.jsp"
                                Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"/>

        </md:IDPSSODescriptor>

      </md:EntityDescriptor>

Login-page rturns status 200:
---------------------------------- New Request ---------------------------------
GET - /mellonEP/login
log_id: W3K1mPGXUE05NZSLo8NuQQAAAEA
server: scheme=(null) hostname=<myserver>.net port=0
pid: 23242, tid: 140669204813568



---------------------------------- New Request ---------------------------------
POST - /mellonEP/postResponse
log_id: W3K1mPGXUE05NZSLo8NuQwAAAEA
server: scheme=(null) hostname=<myserver>.net port=0
.
.
[APLOG_ERR auth_mellon_handler.c:2054] Error processing authn response. Lasso error: [440] The profile cannot verify a signature on the message, SAML Response: StatusCode1="urn:oasis:names:tc:SAML:2.0:status:Success", StatusCode2="(null)", StatusMessage="(null)"

=== Response ===
Status: 400 Bad Request(400)
user:  auth_type=(null)
Response Headers:
  Cache-Control: private, max-age=0, must-revalidate
  Content-Length: 226
  Connection: close
  Content-Type: text/html; charset=iso-8859-1
Response Error Headers:
Environment:
  UNIQUE_ID: W3K1mPGXUE05NZSLo8NuQwAAAEA
  HTTPS: on
  SSL_TLS_SNI: <myserver>.net
-8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- 

from HTTPd-log:
-8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- 
[Wed Aug 15 10:58:52.687613 2018] [auth_mellon:error] [pid 17785:tid 140669020493568] [client 10.92.17.108:65310] Error processing authn response. Lasso error: [440] The profile cannot verify a signature on the message, SAML Response: StatusCode1="urn:oasis:names:tc:SAML:2.0:status:Success", StatusCode2="(null)", StatusMessage="(null)", referer: https://<myidpserver.net>/sso_cond2fa/SingleSignOnService
-8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- 

in mellon-diagnostics-file, MellonSPentityId is always "null"?!

-8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- 
MellonSPentityId (sp_entity_id): (null)
-8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- 

In MellonSPMetadataFile-file it is defined:
-8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<EntityDescriptor
 entityID="https://<myserver>.net"
 xmlns="urn:oasis:names:tc:SAML:2.0:metadata">
 <SPSSODescriptor
   AuthnRequestsSigned="true"
   WantAssertionsSigned="true"
   protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
-8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- -8<- 

Do you have any suggestions? maybe on our "SP"-side or at IdP?

**Comment by Hobbyadmin** [comment]
Problem is solved on IDP Side.  We changed the metadata and so the postResponse works fine.

**Comment by ddarling85** [comment]
Hi @Hobbyadmin,

Can you provide some specifics on what changes you made IdP side to resolve this issue?  We're running into something very similar.
