### ISSUE TITLE
SAML RePost page : add message and template feature

### ISSUE THREAD

**Issue by brenard** [Uninett/mod_auth_mellon#176]
Hello,
Currently, in a browser supporting javascript, the SAML RePost page is completely empty. It's could be misleading for the user. I think it's could be a good idea to just add a message like "Please wait" or something like that. Idealy, it's could be awesome to have possibility to configure a custom template page.
Regards,
Benjamin

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
