### ISSUE TITLE
 signal Segmentation fault (11)

### ISSUE THREAD

**Issue by zivziv** [UNINETT/mod_auth_mellon#18]
I get  signal Segmentation fault (11) when putting MellonIdPMetadataFile file into configuration. the file content is here

```xml
<?xml version="1.0" encoding="UTF-8"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="_78678127e2d3d7d838adeabc4da5784e" entityID="https://sso.skyfence.com/89E601A21F6A852E4F454AFC62E08C11">
 <md:IDPSSODescriptor WantAuthnRequestsSigned="false">
  <md:KeyDescriptor use="signing">
   <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <ds:X509Data>
     <ds:X509Certificate>.....</ds:X509Certificate>
    </ds:X509Data>
   </ds:KeyInfo>
  </md:KeyDescriptor>
  <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" ResponseLocation="https://sso.qa-lab-linux7.skyfence.local/login?from=89E601A21F6A852E4F454AFC62E08C11&amp;action=LOGOUT"/>
  <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" ResponseLocation="https://sso.qa-lab-linux7.skyfence.local/login?from=89E601A21F6A852E4F454AFC62E08C11"/>
  <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" ResponseLocation="https://sso.qa-lab-linux7.skyfence.local/login?from=89E601A21F6A852E4F454AFC62E08C11"/>
  <saml2:Attribute xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" Name="Skyfence.AuthenticatingAuthority" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
 </md:IDPSSODescriptor>
</md:EntityDescriptor>
```

can you please try to see what is wrong?

**Comment by olavmrk** [comment]
It looks like your metadata content didn't survive the GitHub issue reporting field. Could you upload it somewere else, and link it here? E.g. at https://gist.github.com/?

**Comment by zivziv** [comment]
![skyfenceidp_saml_metadata xml](https://cloud.githubusercontent.com/assets/11160180/6349134/0112982c-bc30-11e4-8234-7ad4c3982f80.png)

I uploaded it and rename it to png please rename it to XML.

**Comment by jaimeperez** [comment]
@zivziv I've edited your comment to display the SAML metadata correctly.

**Comment by zivziv** [comment]
I would appreciate your help since I am new to mod_mellon module and I tried to follow your short guide step by step and i am getting segmentation fault.

What other data do you need?

Thanks

Ziv

**Comment by olavmrk** [comment]
Hi,

running through a XML schema validator, it finds the following errors:

```
Validation of gistfile1.xml failed:
gistfile1.xml:3: Element '{urn:oasis:names:tc:SAML:2.0:metadata}IDPSSODescriptor': The attribute 'protocolSupportEnumeration' is required but missing.
gistfile1.xml:11: Element '{urn:oasis:names:tc:SAML:2.0:metadata}SingleLogoutService': The attribute 'Location' is required but missing.
gistfile1.xml:12: Element '{urn:oasis:names:tc:SAML:2.0:metadata}SingleSignOnService': The attribute 'Location' is required but missing.
gistfile1.xml:13: Element '{urn:oasis:names:tc:SAML:2.0:metadata}SingleSignOnService': The attribute 'Location' is required but missing.
```

My guess is that the cause of the segmentation fault is the missing `Location` attribute on the `SingleSignOnService` endpoints. Without that attribute we don't have any place to send the authentication request to.

**Comment by olavmrk** [comment]
Regarding the segmentation fault -- I do not get a segmentation fault, but rather an error due to it being unable to load the metadata:

```
(process:9224): Lasso-WARNING **: 2015-02-24 13:49:11   Cannot load metadata from /etc/apache2/mellon/gistfile1.xml
[Tue Feb 24 13:49:11 2015] [error] [client 158.38.62.107] Error adding metadata "/etc/apache2/mellon/gistfile1.xml" to lasso server objects: Failed to add new provider..
[Tue Feb 24 13:49:11 2015] [error] [client 158.38.62.107] Error adding IdP to lasso server object. Please verify the following configuration directives: MellonIdPMetadataFile and MellonIdPPublicKeyFile.
```

That error makes more sense than the segmentation fault. Not sure why you are getting a segmentation fault instead, but in any case, the proper fix is to get correct metadata from your IdP.

**Comment by zivziv** [comment]
Where can I get XML schema?

**Comment by zivziv** [comment]
Can you also send me a working IDP metadata?

**Comment by zivziv** [comment]
I added the location and I still get segmentation fault when trying to access a folder protected by mod_mellon.

Can someone take a look?

**Comment by olavmrk** [comment]
The XML schemas are located at the OASIS security page: https://wiki.oasis-open.org/security/FrontPage

But in any case, you shouldn't need them unless you are validating the XML yourself.

For a working IdP metadata file, you can test using the Feide OpenIdP: https://openidp.feide.no/simplesaml/saml2/idp/metadata.php?output=xhtml

Regarding your question whether we can take a look -- we cannot log into your server and look at the problem for you.

**Comment by zivziv** [comment]
Hi Guys
Thanks a lot now I am able to get to the login page of my IDP but when I am login I redirect to /mellon although I need to be redirected to other path.

here is my link:

https://sso.qa-lab-linux7.skyfence.local/login?from=89E601A21F6A852E4F454AFC62E08C11&SAMLRequest=hVJdS8MwFP0rJe9tk67turBO0i8YqIiKD75IrJkLpsnMTdX9e9MOYb4oBALnnsM95yRr4IM6UDa6vb4V76MAF3wNSgOdByUaraaGgwSq%2BSCAup7esatLmkSYHqxxpjcKnUn%2BVnAAYZ00GgXbpkRPVU4IXqxYw7oVW3ZpS7q2qopFVWckY9UCBQ%2FCgueXyMu9CGAUWw2Oa%2BchTLIQJ2GS3mNMSeHPIwoan0Fq7mbV3rkD0DgGMNE7DxV%2FDpXU49cygrfjTuheRMr0XMXKvEp9sbNmKItVm2PCEtLlrMiSNu3SLGVdnSctLmpCUFAbDWJy8FfW%2FkSi%2FWitv0M5HJTspUNBZ2wv5spLtOMKxBTsxncjP8QPsllPbdI5sN38xCCrJCJ5ES1JRBY4Ho6tdtIdt806PqevT6967T1tmxvj1x6npQP%2Fx%2FKEyJdwN1Ops1yD9NZRwJQyn7UV3HmDzo4CxZvTyt9%2FZ%2FMN&RelayState=https%3A%2F%2F192.168.71.130%2Fziv

**Comment by olavmrk** [comment]
Hi,

the login response is supposed to be sent to .../mellon/postResponse. That handler will process the login response and then redirect to the URL included in the RelayState parameter from the IdP.

**Comment by zivziv** [comment]
ok, sorry for my lack of knowledge but I just need to connect it to a protected folder in the apache so after I try to access a protected folder it is being redirected to the IDP after login success back to my page
Who should maintain this handler /mellon/postResponse ? I use this example

https://github.com/UNINETT/mod_auth_mellon/wiki/GenericSetup

**Comment by zivziv** [comment]
It is working thanks a lot for your help!!!!
