### ISSUE TITLE
Question: Third-party AA lookup support in mod_auth_mellon?

### ISSUE THREAD

**Issue by spaetow** [Uninett/mod_auth_mellon#181]
Hej! I've tried out mod_auth_mellon and found it pretty useful. One thing that I don't see documented (perhaps it's not supported) is how I can do a third-party attribute authority lookup (similar to the Shibboleth SimpleAggregation type of AttributeResolver). Does mod_auth_mellon support something like this?

**Comment by olavmrk** [comment]
No, there is no support for SAML 2.0 AttributeQuery or anything similar in mod_auth_mellon.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
