### ISSUE TITLE
One Service Provider and multiple Apache VirtualHosts? - AssertionConsumerService

### ISSUE THREAD

**Issue by joelhoward** [Uninett/mod_auth_mellon#185]
I'm not sure if this is even possible or if we are going in the wrong direction on this... so please bear with me.

Background: We are a University that is migrating away from a hybrid Shibboleth/CoSign SSO environment in-favor of WSO2.  Currently my group has several(30+) custom applications that each reside on their own subdomain(two Apache servers, multiple vhosts) and were previously protected by either CoSign or Shib.  

I am in the process of migrating those custom applications over to WSO2 utilizing SAML 2.0 for SSO.  The first few I created individual service providers on the IDP and set up the VirtualHosts independently with their own service provider... no problem.  Well now we have gotten into custom claim mapping and more involved configurations.  I now started wondering if there is a more streamlined approach.

**So my thought was to use one service provider for each web application server and re-use that service provider for each individual application(unique subdomains).  This is where I'm not sure if I'm going in the wrong direction.**

I have it half-working this way by copying the sp's metadata file, creating a new metadata file, and changing the AssertionConsumerService location to match the individual virtualhost's URL.

Example:

Change:
` <AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://web1.university.edu/sso/postResponse" index="0"/>`

To:
` <AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://web2.university.edu/sso/postResponse" index="0"/>`

With basic testing this appears to work.  However, now I have multiple metadata files that do not match and it definitely doesn't feel right.  

Next I looked into the index attributee for AssertionConsumerService... which I thought might work but I do not see an Apache directive provided for mod_auth_mellon for defining the index to use for the SAML request. 

Looking at this issue #3 it looks like the AssertionConsumerService is indeed being passed. The docs for the function: http://lasso.entrouvert.org/documentation/api-reference/lasso-LassoProvider.html#lasso-provider-get-assertion-consumer-service-url it looks like the second arguement is a service_id... would this reference the index?  mod_auth_mellon is setting that to NULL.

Am I going about this all wrong and just stick with creating an SP for each application?  Is there a way to implement a selected index from the VirtualHost conf for AssertionConsumerService?

Thanks!

**Comment by joelhoward** [comment]
To add to this... we are doing something similar with Shibboleth
`<ApplicationOverride id="web1" entityID="https://web1.university.edu/shibboleth"/>
<ApplicationOverride id="web2" entityID="https://web2.university.edu/shibboleth"/>`
https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPApplicationOverride#NativeSPApplicationOverride-MetadataforanExistingSP

**Comment by joelhoward** [comment]
And I got it working with a single metadata file with the following directives:
`MellonRedirectDomains [self] *.university.edu
MellonCookieDomain university.edu`

Still wondering if this is a valid approach?

**Comment by olavmrk** [comment]
Hi,

if you are going to have a single SP covering multiple domains, the approach you have taken is the way to go. Note that it will only work as long as you can set a cookie covering all the domains.

Best regards,
Olav Morken
Uninett / Feide

**Comment by joelhoward** [comment]
Thank you for confirming that the approach I am implementing is the way to go @olavmrk.
