### ISSUE TITLE
IDP requires that either both AssertionConsumerServiceURL and ProtocolBinding or neither

### ISSUE THREAD

**Issue by itewk** [Uninett/mod_auth_mellon#187]
https://github.com/Uninett/mod_auth_mellon/blob/6358a5169762ef7b89d8b6d0f1a99b006f0fdd2f/auth_mellon_handler.c#L2859-L2862

Currently the ProtocolBinding is not being set but the AssertionConsumerServiceURL is but the IDP we are working with requires that either both are set, or neither. This block of code says that the ProtocolBinding because there is no feature in `lasso` to do so and that its `not strictly required` but in our case it is. So, what do we do?

**Comment by itewk** [comment]
it would seem that https://lasso.entrouvert.org/documentation/api-reference/lasso-LassoProvider.html still does not have any way of getting the ProtocolBinding

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
