### ISSUE TITLE
Question: mod_auth_melon Returning NameId null

### ISSUE THREAD

**Issue by sithara** [Uninett/mod_auth_mellon#194]
I'm using mod_auth_melon with okta. The request headers returned does not return the nameid,  however it returns the email. In the saml response  I can see that the nameid returned in the body is in unspecified format and it has value, could you please suggest on how I can validate if my response is valid? Is the nameid in the saml xml body same as the one in header ?

Could you please help me debug this issue ?

**Comment by thijskh** [comment]
It is a bit hard to help without any configs.

All I can say is that in the default configuration, the name ID will be in the `REMOTE_USER` environment variable. Is that what you are reading?

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
