### ISSUE TITLE
Include idP attribute in MellonDefaultLoginPath 

### ISSUE THREAD

**Issue by jasonlyle88** [Uninett/mod_auth_mellon#195]
Maybe I'm missing something simple, but I can't figure out any way to do this:

I want to set the **MellonDefaultLoginPath** based on an attribute (_MELLON_MyAttr_). I have tried all kinds of different things, without any luck:

- MellonDefaultLoginPath /ords/f?p=%{MELLON_MyAttr}
- MellonDefaultLoginPath /ords/f?p=%{MELLON_MyAttr}e
- MellonDefaultLoginPath /ords/f?p=%{ENV:MELLON_MyAttr}
- MellonDefaultLoginPath /ords/f?p=req('MELLON_MyAttr')
- MellonDefaultLoginPath /ords/f?p=reqenv('MELLON_MyAttr')
- MellonDefaultLoginPath /ords/f?p=v('MELLON_MyAttr')

But all of those fail to replace _MELLON_MyAttr_. Is there any way to do this?

My work around is that I set a **MellonDefaultLoginPath** to a **Location** directive that only containes a **RewriteRule**, but that seems sort of overkill.

Thanks for any help you can provide (and thanks for a great tool!)

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
