### ISSUE TITLE
serialize eduPersonTargetedId to string

### ISSUE THREAD

**Issue by fkooman** [Uninett/mod_auth_mellon#197]
I was wonder how to serialize the eduPersonTargetedId with mod_auth_mellon. It would be nice if the same thing where to happen as with Shibboleth, i.e.: `{IdP entityID}!{SP entityId}!{user ID}`. Is this currently possible?

Or is there any other way to make this easy? Currently the HTTP header `MELLON_urn:oid:1_3_6_1_4_1_5923_1_1_1_10` contains the raw XML...

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
