### ISSUE TITLE
mod_auth_mellon Header Encryption

### ISSUE THREAD

**Issue by singhmann1** [Uninett/mod_auth_mellon#198]
Once we strip the user attributes such as email and entitlements from the SAML 2.0 Response we pass these to the application tier. Currently I can only see option to pass these as cleartext values in the headers.
Please let me know how we can pass these using encryption to the application tier to prevent someone from bypassing the apache tier and going straight to the application?
Thanks In Advance

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
