### ISSUE TITLE
[RFE] map oid to human name

### ISSUE THREAD

**Issue by jcpunk** [Uninett/mod_auth_mellon#199]
With the default shibboleth SP I can provide an xml file that translates the OIDs into names.[1]

I'd love to do the same with mod_auth_mellon

Mellon provides:

MELLON_urn:oid:0.9.2342.19200300.100.1.3 	riehecky@fnal.gov
MELLON_urn:oid:0.9.2342.19200300.100.1.3_0 	riehecky@fnal.gov
MELLON_urn:oid:0.9.2342.19200300.100.1.1 	riehecky
MELLON_urn:oid:0.9.2342.19200300.100.1.1_0 	riehecky
MELLON_urn:oid:1.3.6.1.4.1.5923.1.1.1.6 	riehecky@fnal.gov
MELLON_urn:oid:1.3.6.1.4.1.5923.1.1.1.6_0 	riehecky@fnal.gov
MELLON_urn:oid:2.5.4.42 	Patrick
MELLON_urn:oid:2.5.4.42_0 	Patrick
MELLON_urn:oid:2.5.4.4 	Riehecky
MELLON_urn:oid:2.5.4.4_0 	Riehecky 

Where I would prefer:

MELLON_EMAIL    riehecky@fnal.gov
MELLON_EMAIL_0  riehecky@fnal.gov
MELLON_USERID   riehecky
MELLON_USERID_0         riehecky
MELLON_eppn     riehecky@fnal.gov
MELLON_eppn_0   riehecky@fnal.gov
MELLON_NAME_FIRST       Patrick 
MELLON_NAME_FIRST_0     Patrick 
MELLON_NAME_LAST        Riehecky
MELLON_NAME_LAST_0      Riehecky 

[1] https://wiki.shibboleth.net/confluence/display/IDP30/Human+Readable+Attribute+Names

**Comment by olavmrk** [comment]
Hi,

have you tried the `MellonSetEnv` option? E.g.:

```
MellonSetEnv EMAIL urn:oid:0.9.2342.19200300.100.1.3
```

**Comment by jcpunk** [comment]
I've looked at that, but I've got a significant number of attributes (about 60) that are getting fed into my applications.  My IDP is providing the XML file for shibd's translations.  I could build up a script to convert them, but I was hopeful I could just fall back to the XML file....

**Comment by olavmrk** [comment]
I don't really see us adding support for loading a Shibboleth configuration file into mod_auth_mellon -- it would be rather complicated, and we cannot support many of the features that Shibboleth supports in any case, so I think it would quickly just become confusing for users.

My suggestion would be to write a XSLT-script or something to transform the XML into a list of `MellonSetEnv`-options, but I don't really know XSLT, so I don't know how feasible it is.

**Comment by jcpunk** [comment]
Such an XSLT is probably doable.  If I whip one up, would it be possible to get it into mod_auth_mellon for folks (so they don't have to build their own)?
