### ISSUE TITLE
Option to disable sending of Cache-Control header

### ISSUE THREAD

**Issue by olavmrk** [UNINETT/mod_auth_mellon#2]
We should provide a way to disable sending of Cache-Control headers.

Normally you need Cache-Control headers in order to make logout work properly. However, in some cases the application itself may want to send its own Cache-Control header. In that case mod_auth_mellon shouldn't set any Cache-Control header.

Migrated from: https://code.google.com/p/modmellon/issues/detail?id=25

**Comment by jsirex** [comment]
Any updates on this?

**Comment by olavmrk** [comment]
I haven't had time to look at implementing an option for this. Since we haven't had any need for such an option locally, I haven't been able to prioritize this. If someone else wants to contribute a patch, that would be great.

**Comment by jsirex** [comment]
Got it :)
