### ISSUE TITLE
Redirecting to IDP without SAML request

### ISSUE THREAD

**Issue by cpatel-secureauth** [Uninett/mod_auth_mellon#202]

**Comment by thijskh** [comment]
Is this a question, or?

**Comment by cpatel-secureauth** [comment]
Yes this is a question?
It is not passing SAML request when it is redirects from https://mellon_server/secret/ to https://idpserver.com/xyz

**Comment by thijskh** [comment]
Can you share your configuration?

**Comment by thijskh** [comment]
You have configured a discoveryURL:
        MellonDiscoveryURL "https://xyz.com/test.aspx"

Is that not the URL the user is redirected to instead of the IdP? It's a bit hard to tell when the values are anonymized.

**Comment by cpatel-secureauth** [comment]
This is not an actual url. 
My url is not an accessible to internet, that's why I have added test url in file when I sent you.

**Comment by thijskh** [comment]
Yes, but my question is whether you have configured the MellonDiscoveryURL to be the URL of your IdP. Because if you have, this is not correct and this would cause people to get redirected to this URL without a SAMLRequest. So in that case, comment out this setting.

**Comment by cpatel-secureauth** [comment]
If I'll comment MellonDiscoveryURL in config file then how it will redirect to IDP?  Do I need to configure  any other setting when I hit https://mellon_server/secret/ then it will go to IDP for login

**Comment by cpatel-secureauth** [comment]
Thank you very much Thijs for your help.

I am getting SAML request after commenting MellonDiscoveryURL.

I am closing this issue.
