### ISSUE TITLE
refuses to generate SP metadata until an IdP is configured

### ISSUE THREAD

**Issue by baszoetekouw** [Uninett/mod_auth_mellon#204]
mod_auth_mellon currently refuses to serve SP metadata until an IdP is configured.  This leads to annoying bootstrap issues, because in some cases it is necessary (or at least more convenient) to deploy an SP before the IdP is available.

The following error is generated when requesting mod_auth_mellon's metadata when no IdP is specified (yet):
```
[Tue Apr 16 14:54:01.896072 2019] [:error] [pid 103210] [client 145.101.114.22:47662] Error adding IdP to lasso server object. Please verify the following configuration directives: MellonIdPMetadataFile and MellonIdPPublicKeyFile.
```

Obviously, the IdP metadata is not required to generate SP metadata.  Adding dummy IdP-metadata works around the issue, but it would be nice if mod_auth_mellon would just generate its metadata regardless of the IdP configuration.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
