### ISSUE TITLE
MellonOrganization* values require ampersand to be escaped

### ISSUE THREAD

**Issue by dnmvisser** [Uninett/mod_auth_mellon#206]
When any of the MellonOrganization* configuration options contains an ampersand (`&`) character, the web server says 500 and logs:

> Error initializing lasso server object. Please verify the following configuration directives: MellonSPMetadataFile and MellonSPPrivateKeyFile.

For example this fails:

`MellonOrganizationDisplayName "GÉANT Trust & Identity Operations"`

I've confirmed these configuration options to be affected:

- MellonOrganizationName
- MellonOrganizationDisplayName
- MellonOrganizationURL

Interestingly, HTML escaping fixes the problem. So this works:

`MellonOrganizationDisplayName "GÉANT Trust &amp; Identity Operations"`

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
