### ISSUE TITLE
error when compiling mod_auth_mellon-0.14.2

### ISSUE THREAD

**Issue by birgerunell** [Uninett/mod_auth_mellon#216]
configuring latest version of mod_auth_mellon-0.14.2 on httpd-2.4.41 (with openSSL)
have PKG_CONFIG_PATH=/usr/local/lib/pkgconfig in my env
where /usr/local/lib/pkgconfig have:
lasso.pc
libcrypto.pc
libcurl.pc
libssl.pc
libxml-2.0.pc
openssl.pc
sqlite3.pc
xmlsec1-gcrypt.pc
xmlsec1.pc

using this configuration command:
./configure --prefix=/root/mellon/build/mod_auth_mellon-0.14.2 

after make, I got below error:

/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
apxs:Error: Command failed with rc=65536
.
make: *** [mod_auth_mellon.la] Error 1

I'm not using --with-apxs2 as httpd-2.4.41 only have apxs (/root/mellon/build/httpd-2.4.41/bin/apxs)

thank you,
Birger

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
