### ISSUE TITLE
auth_mellon and shibboleth 

### ISSUE THREAD

**Issue by abuissonnet** [UNINETT/mod_auth_mellon#222]
Hello, yesterday I tried to use mellon sso for one website, worked like a charm. 

However, when we tried mellon on another machine already hosting couple websites using shibboleth proxy services, the auth_mellon when activated seems to take over the shibboleth module and while our site using mellon was working just fine, it disabled the saml auth for the others using shibboleth. 

Not sure if this is a shibboleth or mellon related question, 

any idea on this ? 

Thanks for your help. 

(PS : Linux Debian 9 standard apache2 config)

**Comment by abuissonnet** [comment]
Issue still pending but I got things working by disabling auth_mellon from apache (a2dismod auth_mellon) and loading it only inside the website virtualhost using LoadModule.

**Comment by abuissonnet** [comment]
Any update on this issue please ? Your channel looks quite dead.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
