### ISSUE TITLE
Option to start indexing multi-valued attributes from 1 instead of 0

### ISSUE THREAD

**Issue by adelton** [UNINETT/mod_auth_mellon#24]
Currently when mod_auth_mellon creates environment variables for multi-valued attributes, it indexes the values starting with 0. In mod_lookup_identity, which does similar functionality based on values returned by SSSD, the values are indexed starting from 1 (https://github.com/adelton/mod_lookup_identity/blob/master/mod_lookup_identity.c#L168, the ++start is used). We could change mod_lookup_identity, except codebases of Foreman and Spacewalk projects have already been modified to use the numbering scheme starting from 1.
Hence an RFE to add option to enable numbering in mod_auth_mellon to start at 1.

**Comment by olavmrk** [comment]
Hi, I have merged your pull request now, so closing this issue.
