### ISSUE TITLE
Different separator for MellonMergeEnvVars On

### ISSUE THREAD

**Issue by adelton** [UNINETT/mod_auth_mellon#27]
When ```MellonMergeEnvVars On``` is used and multiple values get concatenated, mod_auth_mellon uses semicolon: https://github.com/UNINETT/mod_auth_mellon/blob/master/auth_mellon_cache.c#L620. When consumption of multivalued data in ManageIQ was implemented, the code assumed colon (we used http://www.freeipa.org/page/Environment_Variables#Proposed_Additional_Variables as the basis for the work).
I'd like to propose a way to change the separator in mod_auth_mellon.
Before I show a patch, I'd like to ask if you'd prefer second (optional) parameter to MellonMergeEnvVars, so to achieve colon-separated behaviour you'd use ```MellonMergeEnvVars On ":"``` or if you'd prefer completely separate configuration directive?

**Comment by olavmrk** [comment]
I think keeping it in the same option makes sense here -- the settings are strongly related, and you would never want to set the separator without also enabling merging of environment variables.

**Comment by adelton** [comment]
Since https://github.com/UNINETT/mod_auth_mellon/pull/29 was merged, let me close this issue.
