### ISSUE TITLE
Error with Apache 2.4

### ISSUE THREAD

**Issue by garudlaksha1** [UNINETT/mod_auth_mellon#31]
Hello,

We did compile against Apache 2.4. But when i reference module in httpd.conf, httpd gives error

Starting httpd: httpd: Syntax error on line 82 of /etc/httpd/conf/httpd.conf: Cannot load modules/mod_auth_mellon.so into server: /etc/httpd/modules/mod_auth_mellon.so: undefined symbol: ap_log_error

Can you please let me know how to resolve this?

**Comment by olavmrk** [comment]
mod_auth_mellon works with Apache 2.4, so it is probably a problem with your development/compilation system. Maybe you have compiled mod_auth_mellon against Apache 2.2 header files?

In any case, this is a bug tracker, not a support forum. Support questions should probably be directed to the mailing list, so I am closing this issue.
