### ISSUE TITLE
mod_auth_mellon fails for Require Valid user

### ISSUE THREAD

**Issue by garudlaksha1** [UNINETT/mod_auth_mellon#32]
Hi,

On Apache 2.4, Mellon seems to be failing with these messages
 [authz_core:debug]  mod_authz_core.c(802): AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[authz_core:debug] [pid 14728] mod_authz_core.c(802): [client 192.150.10.203:8151] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
AH00027: No authentication done but request not allowed without authentication 

When protected directory is hit, mellon sends 303 with /login?ReturnTo=<>&Idp=<> and when this request is hit, above errors are shown. This works perfectly in 2.2 Apache.

**Comment by thijskh** [comment]
I have a set up with Apache 2.4 and `Require valid-user` that works fine. Apache's auth modules have changed between 2.2 and 2.4 so perhaps there's an incompatibility. This is not a support forum, you can contact the mailing list with your question and when doing so, please include the full vhost config.

**Comment by davidcx** [comment]
I am also getting this with the config provided in the README and the standard Apache 2.4 and mod_auth_mellon in Debian Jessie.

**Comment by traylenator** [comment]
For 'Require valid-user' to not give 

```
httpd[8890]: Unknown Authz provider: valid-user
```

check that the  authz_user module is loaded.

You also need authn_core to avoid 
```
Invalid command 'AuthType', perhaps misspelled or defined by a module
```

**Comment by thijskh** [comment]
In the Debian package I could specify authn_core as a required dependency so it will be enabled when you install the modmellon package via APT.

Not so sure about authz_user, since it's not strictly required to run modmellon, and I can only express hard dependencies. Probably that would better be solved in documentation in modmellon's readme.
