### ISSUE TITLE
Compile failure -- wrong end-of-comment

### ISSUE THREAD

**Issue by elygre** [UNINETT/mod_auth_mellon#34]
On line https://github.com/UNINETT/mod_auth_mellon/blame/master/auth_mellon_cache.c#L603, the terminating comment has a space (`* /` instead of `*/`). This gives a compile error:

    auth_mellon_cache.c:606:13: warning: "/*" within comment
    auth_mellon_cache.c: In function ‘am_cache_env_populate’:
    auth_mellon_cache.c:616: error: ‘else’ without a previous ‘if’
    auth_mellon_cache.c: At top level:
    auth_mellon_cache.c:640: error: expected identifier or ‘(’ before ‘if’
    auth_mellon_cache.c:644: error: expected identifier or ‘(’ before ‘else’
    auth_mellon_cache.c:655: error: expected identifier or ‘(’ before ‘if’
    auth_mellon_cache.c:669: error: expected identifier or ‘(’ before ‘if’
    auth_mellon_cache.c:675: error: expected identifier or ‘(’ before ‘}’ token

**Comment by olavmrk** [comment]
Thanks for letting us know! I have now committed a fix, and configured Travis CI so that this shouldn't happen in the future.
