### ISSUE TITLE
Using Mellon for auth on reverse proxy

### ISSUE THREAD

**Issue by sgerlach** [UNINETT/mod_auth_mellon#41]
Hello,

I'm trying to set up a reverse proxy to add SSO authentication in front of a handful of applciations that do not have any authentication. I'm trying to use mellon to integrate with Okta, and I have the initial part of the config sort of set, so that Apache fowards me off to Okta, let's me login, and returns me to Apache, but I'm sort of stuck at this point. I'm thinking I need to add another auth module to Apache for mellon to foward credentials to but I'm unsure. Do you have any guidance or resources that could help with such a setup?

eg
Front end:
user visits server.com/application mellon auth sends to okta/saml for auth
okta/saml posts back to.. apache with some other auth module...?
server.com reverse proxies to back end

backend:
application.domain.com (no auth modules here anywhere)

**Comment by thijskh** [comment]
This is a bug tracker, not a support forum. Could you please direct your support question to the project mailing list? https://postlister.uninett.no/sympa/subscribe/modmellon

**Comment by sgerlach** [comment]
Gotcha. Thank you
https://postlister.uninett.no/sympa/arc/modmellon/2015-08/msg00001.html
