### ISSUE TITLE
Remove deprecated feide attribute decoder

### ISSUE THREAD

**Issue by thijskh** [UNINETT/mod_auth_mellon#42]
mod_auth_mellon contains a configration directive MellonDecode which decides to either decode attribute values with the "feide" method or with "none" (a no-op). Maybe is it time now to remove this function which has been deprecated for over 3 years now?

One could consider to just remove the 'feide' option and code (keep accepting the MellonDecode directive in config), or the MellonDecode directive altogether, which removes more code but might require people to update their configs if they have the directive.

If desired I can provide a pull request.

**Comment by olavmrk** [comment]
Yes, finally getting rid of the method makes sense. Unfortunately I see that I only deprecated the "feide" value, and not the complete option, so I don't think we can remove the option itself. If you would provide a patch that removes the "feide"-value and associated functions that would be great. I guess the documentation should also be updated, but I don't really know what it should say. Something about the option no longer being used maybe?
