### ISSUE TITLE
Cert files name wrong when hostname contains a number.

### ISSUE THREAD

**Issue by traylenator** [UNINETT/mod_auth_mellon#43]
When executing *mellon_create_metadata.sh* with a hostname with
a number in the output files are generated incorrectly.

```
# /usr/libexec/mod_auth_mellon/mellon_create_metadata.sh https://melon7.example.org/mellon https://melon7.example.org/mellon                                
Output files:
Private key:               https_melon_.example.org_mellon.key
Certificate:               https_melon_.example.org_mellon.cert
Metadata:                  https_melon_.example.org_mellon.xml
Host:                      melon7.example.org

Endpoints:
SingleLogoutService:       https://melon7.example.org/mellon/logout
AssertionConsumerService:  https://melon7.example.org/mellon/postResponse
```

**Comment by olavmrk** [comment]
Hi,
could you open a pull request with this change? It makes it easier to merge the change, as well as clearly indicating that you want the change in that commit to be added to mod_auth_mellon.

**Comment by olavmrk** [comment]
Ah, sorry -- didn't see your pull request before I posted that comment.

**Comment by traylenator** [comment]
Thanks, just FYI https://github.com/puppetlabs/puppetlabs-apache/pull/1189 was just merged.
