### ISSUE TITLE
$_SERVER['MELLON_*] variables are missing

### ISSUE THREAD

**Issue by konstantinvlasenko** [UNINETT/mod_auth_mellon#46]
Hi all,
I am using SimpleSAMLphp as identity provider. I have another SP which uses SimpleSAMLphp as well. And this works.
Now I want to try to use this mod_auth_mellon instead.
It seems like the redirect chain works. But then the code below doesn't print anything:
``` php
<?php
header('Content-Type: text/plain');
foreach($_SERVER as $key=>$value) {
  if(substr($key, 0, 7) == 'MELLON_') {
    echo($key . '=' . $value . "\r\n");
  }
} 
```
What I am doing wrong?

**Comment by olavmrk** [comment]
This is most likely a configuration problem on your end. My guess is that the PHP code is not executed under mod_auth_mellon. In any case, this is a bug tracker, and not a  support forum. You are probably better of sending a question to the mailing list. You should also include information about your configuration.
