### ISSUE TITLE
Session Timeout.

### ISSUE THREAD

**Issue by walkerrIjet** [UNINETT/mod_auth_mellon#47]
Does Mod_auth_mellon suppor idle session timeout? 

There is a # MellonSessionLength config value, but when it was set and tested, the session did not timeout. Is it possible to expire the cookie after a preset idle time or given time? There is nothing currently in the readme or classes that suggest the ability to perform a session timeout. 

Thank you.

**Comment by olavmrk** [comment]
Just copy-pasting the answer I just sent to the mailing list here:

> there is no direct way to set the session lifetime in mellon. In the end, the session lifetime is decided by the IdP. If you have a shorter session in mod_auth_mellon than on the IdP, you just end up with a round-trip to the IdP where you are authenticated automatically.
