### ISSUE TITLE
Mailing list URLs not working

### ISSUE THREAD

**Issue by surfnet-niels** [UNINETT/mod_auth_mellon#57]
The README.md lists a mailinglist for support. These are however not working :(

"There's a mailing list for discussion and support.
To subscribe: https://postlister.uninett.no/sympa/subscribe/modmellon
List archives: https://postlister.uninett.no/sympa/arc/modmellon"

What is the correct location of the mod_mellon mailing list?

**Comment by thijskh** [comment]
It seems the location has been changed to https://sympa.uninett.no/lists/uninett.no/info/modmellon

**Comment by olavmrk** [comment]
Thanks for letting us know. I have updated the README file.

There is a redirect in place, bit it appears to not work correctly. I'll let those that are responsible know.
