### ISSUE TITLE
On Debian mod_mellon 0.9.1 doesn't works

### ISSUE THREAD

**Issue by jsirex** [UNINETT/mod_auth_mellon#6]
On Debian mod_mellon 0.9.1 requires liblasso >=2.4.1

But seems it works only if I use liblasso 2.3.6 and downgrade mellon.

I know, that is also packaging issue, but you've declarated as liblasso >= 2.0

And I cannot figure out why it doesn't works with 2.4.1

```
[Tue Sep 09 15:40:45.403639 2014] [:error] [pid 14093:tid 140151334356736] [client 10.6.176.16:45024] Error processing authn response. Lasso error: [-427] When looking for an assertion we did not found it., referer: https://login.sso.projects.com/adfs
/ls/

(process:14093): Lasso-CRITICAL **: 2014-09-09 15:40:45 (xml.c/:1647) Trying to add to a GList* a non GObject pointer dest=*list src=subnode
```

On production I'm using 0.7.0. But I cannot upgrade :(

**Comment by thiyagarajank** [comment]
@jsirex The given link is not working. Can you share the working link, as we have the same issue?

**Comment by jsirex** [comment]
@thiyagarajank Which link? To a branch? I know nothing about it because it was just quote. May be branch deleted or merged.

Currently I have the same issue. Latest released liblasso doesn't work. Oldest available mod_mellon requires 2.4.x, which is latest, an still doesn't work.

**Comment by thiyagarajank** [comment]
@jsirex We have 2.4.1 lasso with mellon 10 in ubuntu 14.04. The SP not accepting anything other than sAMAccountName from ADFS. Is there any workaround? 

Seems the branch deleted and not able to find the patch for it :(

**Comment by jaroslawp** [comment]
These are the patches we use:

http://repos.entrouvert.org/lasso.git/commit/?id=4ad4b673940ef72de1a62d7589cd0d86290086b1

http://repos.entrouvert.org/lasso.git/commit/?id=a27d1686b387a045607b5f0802001ea8863342cb

Cheers

Jarek

**Comment by thiyagarajank** [comment]
@jaroslawp Not able to install these in Ubuntu, is there any document / steps to install?

**Comment by thiyagarajank** [comment]
@jaroslawp the error

CC       lasso.lo
In file included from lasso.c:76:0:
lasso.c: In function 'lasso_check_version':
../config.h:53:29: error: 'UNKNOWN' undeclared (first use in this function)
 #define LASSO_VERSION_MAJOR UNKNOWN

**Comment by sabisky** [comment]
I have the same error as @thiyagarajank with ubuntu
I'm trying to install lasso-2.5.1 with ./autogen.sh and make install

Did you find a solution for this?
