### ISSUE TITLE
Support for SHA-256 signatures in AuthnRequest

### ISSUE THREAD

**Issue by mlbiam** [Uninett/mod_auth_mellon#60]
Is there a setting to force mod_auth_mellon to use SHA-256 instead of SHA-1 when signing an AuthnRequest?

**Comment by olavmrk** [comment]
No, there isn't such an option present, so we use whatever the Lasso library uses as a default, which currently is [`http://www.w3.org/2000/09/xmldsig#rsa-sha1`.](http://www.w3.org/TR/xmldsig-core/#sec-PKCS1).

I don't have time to implement this at the moment, but I am leaving this issue open as a feature request.

**Comment by specifice** [comment]
Hi Olav,
RSA-SHA256 is only available since lasso 2.5.1. I tried to support both options (old lasso would end up in sha1, new lasso would go with sha256) via
`AC_CHECK_DECL(LASSO_SIGNATURE_METHOD_RSA_SHA256, 
             LASSO_CFLAGS="$LASSO_CFLAGS -DHAVE_SHA256")`
in configure.ac, but it did not work for me. Any ideas how to properly check for LassoSignatureMethod enum value presence on configure phase?

**Comment by mprewitt007** [comment]
We rae experiencing this issue where the current build still defaults to sha-1, when many IDP's are dropping support for this. How do we get lasso /mod_mellon to push to sha-256?

**Comment by shredder12** [comment]
@mprewitt007 New version of liblasso have support for SHA-256. Depending on where you run HTTPD, you can either get packages from recent distribution(Ubuntu xenial), upgrade distribution or just compile your own.

We backported liblasso3 and dependencies from xenial to trusty and it worked.

**Comment by jvlcek** [comment]
Bump. How do we get lasso /mod_mellon to push to sha-256?

**Comment by thijskh** [comment]
Probably the fastest way to resolve it, is to work on the requested changes of PR #105

**Comment by jdennis** [comment]
I believe this was resolved with commit  9b17e5c on  Thu Jan 11 2018. It first appeared in mellon 14.0.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
