### ISSUE TITLE
Fix segmentation fault when installed by Apache graceful restart

### ISSUE THREAD

**Issue by olavmrk** [Uninett/mod_auth_mellon#63]
If the module is activated by a Apache graceful restart, instead of a full restart, the result can be a segmentation fault in the web server on the first request. Steps to reproduce:
1. `apt-get install libapache2-mod-auth-mellon`
2. `a2enmod auth_mellon` (without the suggested restart of Apache)
3. Enable mod_auth_mellon in a site.
4. `service apache2 reload`
5. Send a request to the site that has mod_auth_mellon enabled.

The result is a segmentation fault.

Workaround:
Run `service apache2 restart` after `a2enmod`.

**Comment by osteenbergen** [comment]
Seeing the same issue:
```
# apt-cache show libapache2-mod-auth-mellon
Package: libapache2-mod-auth-mellon
Status: install ok installed
Priority: extra
Section: web
Installed-Size: 151
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 0.11.0-1
Depends: libc6 (>= 2.14), libcurl3 (>= 7.16.2), libglib2.0-0 (>= 2.14.0), liblasso3 (>= 2.4.1), libssl1.0.0 (>= 1.0.0), apache2-api-20120211
Conffiles:
 /etc/apache2/mods-available/auth_mellon.conf 9194924811449578761c9b23e528cf35
 /etc/apache2/mods-available/auth_mellon.load 494aac8b2db9b4c543b9cddeecb99d6e
Description-en: SAML 2.0 authentication module for Apache
 mod-auth-mellon is an Apache module which enables you to authenticate
 users of a web site against a SAML 2.0 enabled IdP. It can grant
 access to paths and provide attributes to other modules and applications.
Description-md5: 4862e66932c68c760e55bf807f636b0c
Original-Maintainer: Thijs Kinkhorst <thijs@debian.org>
Homepage: https://github.com/UNINETT/mod_auth_mellon
```

**Comment by osteenbergen** [comment]
Compiled the library from source and ```apache2ctl restart``` now works. 

Did have an issue with installing dependencies:
```
# apt-get install liblasso3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 liblasso3-dev : Depends: liblasso3 (= 2.4.0-2build1) but 2.4.1-1build1 is to be installed
                 Depends: libxmlsec1-dev but it is not going to be installed
                 Depends: libglib2.0-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I haven't installed ```libapache2-mod-auth-mellon``` myself so I don't know why liblasso3 is a version higher that that the repository has. After downgrading the libraries to the repository supplied version I could install the development package and compile the library.

**Comment by rainerjung** [comment]
I suggest closing this bug as WONTFIX.
Rationale: mod_auth_mellon could be the culprit here, but it is also possible, that another module is responsible for the above crash due to being moved to some other address as a consequence of adding mod_auth_mellon. It is always possible that a module keeps a reference to some function pointer that it retrieves during initial initialization and does not renew it during a graceful restart. So whenever you add or remove modules or change their order, it is possible, that such a function pointer now points to an invalid address, because the addresses of the modules in memory could have moved. So it is good practice to stop-then-start whenever you change the list of activated modules.

**Comment by olavmrk** [comment]
I would at least like to try to reproduce it in a debugger first, and see where it crashes.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
