### ISSUE TITLE
Permanent cookie

### ISSUE THREAD

**Issue by anghelutar** [UNINETT/mod_auth_mellon#65]
Hello,

Is it possible to add an option to have a cookie with an expiration date rather than a session based cookie?

Thank you,
roxana

**Comment by thijskh** [comment]
As far as I know this is currently not possible. It should of course be possible to modify the code in auth_mellon_cookie.c to do so if you want it.

**Comment by olavmrk** [comment]
I don't think this is something that makes sense for mod_auth_mellon. The session lifetime is already inherently limited by how long the session is stored in the shared memory segment in Apache. Expecting the session to live for several days would be rather optimistic.

There is also the matter of session lifetime on the IdP. Normally the IdP also uses a session cookie, which means that if mod_auth_mellon uses a long-lived cookie, you would end up with session lifetime confusion, where the SP thinks the user is logged in, but the IdP doesn't consider the user to be logged in.
