### ISSUE TITLE
Reverse Proxy Setup: Invalid Destination on Response (http/https)

### ISSUE THREAD

**Issue by andreaslang** [UNINETT/mod_auth_mellon#66]
Apache Version: Version: 2.4.7-1ubuntu4.8
Mod Mellon Version: 0.11.0
Lasso Version: 2.5.0

I receive the following error:

```
Invalid Destination on Response. Should be: http://xxx, referer https://yyy
```

The SAML authentication response contains an https URL instead of the expected http.

I pretty much know why this happens. I have two apache instances running. One, serving as reverse proxy and the other the application-apache and mod_auth_mellon. The proxy exposes https to the internet and forwards to the application-apache in my internal network using http. In mod_auth_mellon the URL is constructed using the apache function _ap_construct_url_. It will happily construct the correct url but with http instead of https causing the error.

For the time being, I will probably switch to use https in my internal network but I was wondering if the forwarding of SAML requests should break if the apache instance running mod_auth_mellon uses http while the original request used https. Is there an obvious other solution which I am missing?

I have seen MellonSubjectConfirmationDataAddressCheck but that one does seem to deal with IP addresses.

**Comment by thijskh** [comment]
I believe mod_mellon constructs the URL from Apache's info about the vhost it's serving. I have not tried, but would recommend to try something like `ServerName https://example.org` and/or `SetEnv HTTPS on` in your vhost configuration to see if that helps.

**Comment by andreaslang** [comment]
I will give it a try later today. It would surprise me if the ServerName worked, as the documentation clearly states: _fully-qualified-domain-name_ which would mean no protocol. The SetEnv HTTPS sounds more interesting.

**Comment by olavmrk** [comment]
Actually, the syntax allows https. From the [documentation](https://httpd.apache.org/docs/2.4/mod/core.html#servername):
> Syntax:	ServerName [scheme://]fully-qualified-domain-name[:port]
> [...]
> Sometimes, the server runs behind a device that processes SSL, such as a reverse proxy, load balancer or SSL offload appliance. When this is the case, specify the https:// scheme and the port number to which the clients connect in the ServerName directive to make sure that the server generates the correct self-referential URLs.

**Comment by andreaslang** [comment]
You are right, my brain seems to be a bit slow this morning. 

I just tried it and it seems to work using _ServerName https://mydomain_. I am closing the issue then.
