### ISSUE TITLE
NameID default format

### ISSUE THREAD

**Issue by ghost** [Uninett/mod_auth_mellon#68]
Is there a way to set the NameID format to urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified as default in auto created metadata instead of urn:oasis:names:tc:SAML:2.0:nameid-format:transient

**Comment by thijskh** [comment]
No, this is currently hardcoded. You can of course change it in the source (`auth_mellon_handler.c`) or choose to not use the autogenerated metadata.

**Comment by thiyagarajan-k** [comment]
Is there any plan on changing the default / allowing to set the format in the config section? Like to use it against multiple IDPs in virtual hosts. With web hosting panel access, customising metadata is not user friendly.

**Comment by olavmrk** [comment]
No concrete plans, but since we insert this element into the generated metadata we may want to allow an option for customizing it. I cannot promise that it will be added any time soon though.

**Comment by thiyagarajan-k** [comment]
Thank you

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
