### ISSUE TITLE
Option to return HTTP 401/403 instead of HTTP 303 (for XHR requests only)

### ISSUE THREAD

**Issue by yarki** [UNINETT/mod_auth_mellon#7]
Folks,

Sometimes a session gets expired and any XHR request results in a silent redirect returning IDP login page HTML code (a bit unexpected behavior, requires special handling on client-side).

Would it make sense to return HTTP 401 or 403 in case a request headers contain 
`X-Requested-With: XMLHttpRequest` 
and the session is over? (configurable option)

Relevant links:
https://issues.jboss.org/browse/PLINK-273
http://stackoverflow.com/questions/7042865/what-is-the-common-http-header-for-request-by-js-libs

What are your thoughts? 

Thanks.

**Comment by olavmrk** [comment]
I haven't heard back here, so I am going to assume that my suggestion works. Closing this issue.
