### ISSUE TITLE
IDP environment Tokens are Full URLs

### ISSUE THREAD

**Issue by waynedovey** [UNINETT/mod_auth_mellon#70]
If I view the environment variables request headers on the Server I see the full URL. This causes issues when using these variable. Apache is unable to deal with this correctly. Is this a Mellon bug or something on the IDP side?

Example

MELLON_http://schemas_xmlsoap_org/ws/2005/05/identity/claims/Username=joe@example.com
MELLON_http://schemas_xmlsoap_org/ws/2005/05/identity/claims/Username_0=joe@example.com
MELLON_http://schemas_xmlsoap_org/ws/2005/05/identity/claims/givenname=Joe
MELLON_http://schemas_xmlsoap_org/ws/2005/05/identity/claims/givenname_0=Joe
MELLON_http://schemas_xmlsoap_org/ws/2005/05/identity/claims/surname=Blog
MELLON_http://schemas_xmlsoap_org/ws/2005/05/identity/claims/surname_0=Blog

**Comment by thijskh** [comment]
Mellon will literally use the attribute names as they are sent to the SP. So this is the form the IdP sends. You can verify that with the Firefox SAML Tracer plugin.

They are not valid SAML attribute names. In my situation I receive something like:
MELLON_urn:mace:dir:attribute-def:givenName=Thijs
MELLON_urn:mace:dir:attribute-def:givenName_0=Thijs
MELLON_urn:oid:2.5.4.42=Thijs
MELLON_urn:oid:2.5.4.42_0=Thijs 

I'd recommend investigating why your IdP sends those values. It looks WS-Federation like.

**Comment by olavmrk** [comment]
You can map the attributes to "better" names by using the `MellonSetEnv` option. E.g. something like this:

```
MellonSetEnv "http://schemas_xmlsoap_org/ws/2005/05/identity/claims/Username" "username"
MellonSetEnv "http://schemas_xmlsoap_org/ws/2005/05/identity/claims/givenname" "givenname"
MellonSetEnv "http://schemas_xmlsoap_org/ws/2005/05/identity/claims/surname" "surname"
```

> They are not valid SAML attribute names.

Just a minor note here: They are not valid according to the "MACE-Dir SAML Attribute Profile", which is targeted at the educational sector. It is however not the only SAML 2.0 attribute profile, and those attribute names are valid URIs, which means that they fullfill all requirements for using the `urn:oasis:names:tc:SAML:2.0:attrname-format:uri` SAML 2.0 attribute name format.

**Comment by KevinWhalen** [comment]
@olavmrk, Is that `MellonSetEnv` example for mapping [claimstypes](https://msdn.microsoft.com/en-us/library/microsoft.identitymodel.claims.claimtypes_members.aspx) backwards?

>     # MellonSetEnv configuration directives allows you to map
>     # attribute names received from the IdP to names you choose
>     # yourself. The syntax is 'MellonSetEnv <local name> <IdP name>'.
>     # You can list multiple MellonSetEnv directives.
>     # Default. None set.
>     MellonSetEnv "e-mail" "mail"

`MellonSetEnv "user_principal_name" "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"`
