### ISSUE TITLE
Unable to get Session attributes

### ISSUE THREAD

**Issue by rsabir** [UNINETT/mod_auth_mellon#79]
I have set an environment where WSO2 is IDP and mod_auth_mellon is SP. The SSO works correctly but when I try to retrieve the attributes (the email of user), I got an empty array in $_SESSION(php).
Here's my conf in apache:
```
<VirtualHost *:443>
    ServerName mellon.capgemini-sp.com
    SSLEngine On
    SSLProxyEngine On
    SSLCertificateFile /etc/pki/tls/certs/capgemini-sp.com.crt
    SSLCertificateKeyFile /etc/pki/tls/private/capgemini-sp.com.key
    ProxyRequests Off
    ProxyPassInterpolateEnv On
    ProxyPass /mellon/ !
    ProxyPass /wso2/auth/ !
    ProxyPass / http://localhost:8050/
    ProxyPassReverse / http://localhost:8050/
    #SAML
    <Location /wso2/>
          Require valid-user
          AuthType "Mellon"
          MellonEnable auth
          #MellonVariable "cookie"
          MellonUser "NAMEID"
          #MellonSetEnv "e-mail" "mail"
          #MellonPostReplay On
          MellonIdP "IDP"
          MellonDoNotVerifyLogoutSignature wso2
          MellonSPMetadataFile /opt/mellon/metadata/sp-wso2.xml
          MellonSPPrivateKeyFile /etc/httpd/mellon/mellon.key
          MellonSPCertFile /etc/httpd/mellon/mellon.cert
          MellonIdPMetadataFile /opt/mellon/metadata/wso2.xml
      </Location>
      <Location /wso2/auth/>
          Require valid-user
          AuthType "Mellon"
          MellonEnable auth
          MellonDoNotVerifyLogoutSignature wso2
      </Location>
</VirtualHost>
```
And my simple php file : 
```
<?php session_start(); ?>
<?php include_once("header.php");?>
<div class="container">
  <h2>Mod_auth_mellon</h2>

  <div class="text-right">Hello  <strong><?php print_r($_SESSION);?></strong>

</div>
<?php include_once("footer.php");?>
```

**Comment by olavmrk** [comment]
A couple of things to check:
1. Is your PHP script located under the `/wso2`-directory?
2. Is the reverse proxy functionality used? In that case you need to configure Apache to pass the environment variables through the proxy as HTTP headers.

**Comment by rsabir** [comment]
The response is:
1- Yes I did some echo to see if I load the right page.
2- Yes, I've install mod_aut_mellon on the proxy-server as you can see on the above appache setting. I've also tested this php script in the same server without using a proxy server and it doesn't work : 
```
<VirtualHost *:443>
    ServerName mellon.capgemini-sp.com
    SSLEngine On
    SSLProxyEngine On
    SSLCertificateFile /etc/pki/tls/certs/capgemini-sp.com.crt
    SSLCertificateKeyFile /etc/pki/tls/private/capgemini-sp.com.key
    AliasMatch "^/wso2/$" "/var/www/html/wso2/"

    #SAML
    <Location /wso2/>
          Require valid-user
          AuthType "Mellon"
          MellonEnable auth
          MellonUser "NAMEID"
          MellonIdP "IDP"
          MellonDoNotVerifyLogoutSignature wso2
          MellonSPMetadataFile /opt/mellon/metadata/sp-wso2.xml
          MellonSPPrivateKeyFile /etc/httpd/mellon/mellon.key
          MellonSPCertFile /etc/httpd/mellon/mellon.cert
          MellonIdPMetadataFile /opt/mellon/metadata/wso2.xml
          MellonEndpointPath /wso2/auth/mellon
          MellonRedirectDomains *
      </Location>

      <Location /wso2/auth/>
          Require valid-user
          AuthType "Mellon"
          MellonEnable auth
          MellonDoNotVerifyLogoutSignature wso2
      </Location>
</VirtualHost>
```

**Comment by olavmrk** [comment]
I just noticed the problem with your PHP script -- you try to access the environment variables that mod_auth_mellon sets as if they are PHP session variables. The PHP session is solely under the control of PHP, and environment variables from the web server won't show up there.

Try changing `print_r($_SESSION)` to `print_r($_SERVER)`, and see if you get the environment variables there.

As for the proxy, you need to configure Apache to pass environment variables as request headers. You can do that using the Apache [`RequestHeader`](http://httpd.apache.org/docs/current/mod/mod_headers.html#requestheader) option.

For example, to pass the `MELLON_NAME_ID` environment variable through, add something like this to your proxy configuration:

```
RequestHeader set Mellon-NameID %{MELLON_NAME_ID}e
```

**Comment by rsabir** [comment]
Thank you very much for your help. Indeed, I was using $_SESSION instead of $_SERVER.
