### ISSUE TITLE
Is NameIDFormat in sp-metadata.xml honored?

### ISSUE THREAD

**Issue by monken** [UNINETT/mod_auth_mellon#80]
I have specified NameIDFormat in the sp-metdata.xml file. However, Mellon seems to ignore it and sends urn:oasis:names:tc:SAML:2.0:nameid-format:transient. I'm on version 0.12.

```
<NameIDFormat>
      urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
</NameIDFormat>
```

**Comment by olavmrk** [comment]
I cannot reproduce this. I added `<NameIDFormat>foo</NameIDFormat>` to my SP metadata, and my authentication request then contained:

```
    <samlp:NameIDPolicy Format="foo"
                        AllowCreate="true"
                        />
```

This is initialized by the Lasso library here: https://repos.entrouvert.org/lasso.git/tree/lasso/saml-2.0/login.c?id=v2.5.1#n96
