### ISSUE TITLE
Use ap_strcasestr instead of non-standard strcasestr

### ISSUE THREAD

**Issue by rainerjung** [UNINETT/mod_auth_mellon#82]
Some platforms, e.g. Solaris, do not have strcasestr(). Apache brings a local implementation.  Patch:

    Index: auth_mellon_util.c
    --- auth_mellon_util.c      2016-03-09 10:00:44.000000000 +0100
    +++ auth_mellon_util.c      2016-06-17 23:33:48.474156000 +0200
    @@ -448,7 +448,7 @@
                      match = !ap_regexec(ce->regex, value, 0, NULL, 0);

                 } else if (ce->flags & (AM_COND_FLAG_SUB|AM_COND_FLAG_NC)) {
    -                 match = (strcasestr(ce->str, value) != NULL);
    +                 match = (ap_strcasestr(ce->str, value) != NULL);

                 } else if (ce->flags & AM_COND_FLAG_SUB) {
                      match = (strstr(ce->str, value) != NULL);

The function is available since February 2000 in Apache 1.3 and since March 2000 in Apache 2.0.

Regards,

Rainer

**Comment by olavmrk** [comment]
Hi,

any chance you could submit this patch (and the other patches) as pull requests instead of inline diffs in the comment? It significantly simplifies applying them, and also ensures that the patches get the correct authorship automatically.

**Comment by rainerjung** [comment]
Pull requests created.

**Comment by olavmrk** [comment]
Thanks! I have merged pull request #86.
