### ISSUE TITLE
Fix compiler warnings due to wrong print format specifications

### ISSUE THREAD

**Issue by rainerjung** [UNINETT/mod_auth_mellon#84]
Suggested patch:

    Index: auth_mellon_util.c
    --- auth_mellon_util.c      2016-03-09 10:00:44.000000000 +0100
    +++ auth_mellon_util.c      2016-06-17 23:33:48.474156000 +0200
    @@ -1814,7 +1814,7 @@
                 if (*p != '\"') {
                     *error = apr_psprintf(pool,
                                           "unterminated string begining at "
    -                                      "position %lu in \"%s\"",
    +                                      "position %" APR_SIZE_T_FMT " in \"%s\"",
                                           start-str, str);
                     break;
                 }
    @@ -1840,7 +1840,7 @@
             else {                  /* unrecognized token */
                 *error = apr_psprintf(pool,
                                       "unknown token at "
    -                                  "position %lu in string \"%s\"",
    +                                  "position %" APR_SIZE_T_FMT " in string \"%s\"",
                                       p-str, str);
                 break;
             }
    @@ -1908,7 +1908,7 @@
             return "end of string";
         }

    -    return apr_psprintf(tokens->pool, "\"%s\" at position %lu",
    +    return apr_psprintf(tokens->pool, "\"%s\" at position %" APR_SIZE_T_FMT,
                             APR_ARRAY_IDX(tokens, index, Token).str,
                             APR_ARRAY_IDX(tokens, index, Token).offset);
     }

**Comment by olavmrk** [comment]
Thanks! I have merged pull request #88.
