### ISSUE TITLE
Fix trivial typo in message

### ISSUE THREAD

**Issue by rainerjung** [UNINETT/mod_auth_mellon#85]
Plase => Please. Suggested patch:

    --- auth_mellon_handler.c  2016-03-09 10:00:44.000000000 +0100
    +++ auth_mellon_handler.c       2016-06-19 17:06:50.305647000 +0200
    @@ -3228,7 +3228,7 @@
         if (timeout == -1) {
             ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r,
                           "probe discovery handler invoked but not "
    -                      "configured. Plase set MellonProbeDiscoveryTimeout.");
    +                      "configured. Please set MellonProbeDiscoveryTimeout.");
             return HTTP_INTERNAL_SERVER_ERROR;
         }

**Comment by olavmrk** [comment]
Thanks! I have merged pull request #87.
