### ISSUE TITLE
Add support for HTTP-POST binding when receiving logout messages

### ISSUE THREAD

**Issue by balajirags** [Uninett/mod_auth_mellon#92]
My IDP is sending a HTTP-Post request instead of HTT-Redirect to my apache for logout, because of which i am getting "urn:oasis:names:tc:SAML:2.0:status:RequestDenied". I am not sure if mod auth mellon support HTTP-POST for single logout.

**Comment by olavmrk** [comment]
It doesn't support HTTP-POST for receiving logout messages from the IDP. I think the underlying library supports it, but I don't have the time to implement that now.

I will change the title of the issue to reflect and leave this issue open as a feature request.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
