### ISSUE TITLE
Conditions element in SAML response isn't really optional

### ISSUE THREAD

**Issue by ravikumarrao** [UNINETT/mod_auth_mellon#93]
We have setup the mellon mod on our Apache server for testing an internal SAML 2.0 service. Almost everything went well, except a few misleading messages from lasso, that were only solved when we added more traces and debugged the code. 

**However**, we found one issue in the mellon mod. Looks like the Conditions element is always expected, even though in the [specifications ](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) it is mentioned [**Optional**] in Page 16 at line 569. 

The code fails at line 1363 in **function am_validate_conditions** of **auth_mellon_handler.c** with error "_Wrong type of Conditions node._".

**Comment by olavmrk** [comment]
Hi,
you are right -- the `<saml:Conditions> element isn't required, neither in the main spec nor in the Web Browser SSO Profile document. I have now pushed a fix for this issue in 9e89195.

**Comment by ravikumarrao** [comment]
Thanks @olavmrk!
