### ISSUE TITLE
How to get SAML response attributes converted to HTTP headers 

### ISSUE THREAD

**Issue by alex9125** [UNINETT/mod_auth_mellon#94]
Hello, 

Sorry for a might be obvious question - it's my first mellon project.

We are using Apache 2.2 with mod_mellon. We are getting SAML response from our IdP provider and can see all the attributes but cannot convert them to HTTP headers to pass to our web application.

Here is the section of our httpd.conf which deals with mellon.

 \<Location /claim-portal>
    RewriteEngine on
    RequestHeader set samlresponse %{MELLON_SAML_RESPONSE}e
    RequestHeader set samlsession %{MELLON_SESSION}e
    Require valid-user
    AuthType "Mellon"
    MellonEnable "auth"    
    MellonSamlResponseDump On
    MellonUser "NameID"
    **RewriteRule .* - [E=RU:%{code}]
    RequestHeader set UserToken %{RU}e**
\</Location> 

The attribute we need is "code". I tried replacing it with MELLON_CODE in RewrireRule  without any luck - my UserToken is still null.

What am I doing wrong here?

**Comment by olavmrk** [comment]
Hi,

first of all, this is a bug tracker and not a support forum. You should probably send an email to the mailing list instead.

However, a short suggestion that you can try:

```
RequestHeader set UserToken %{MELLON_code}e
```

There should not be any need for a `RewriteRule` here.
