### ISSUE TITLE
Session Cache across apache reloads

### ISSUE THREAD

**Issue by darkfiberiru** [Uninett/mod_auth_mellon#95]
It would be nice to be able to have the choice to restart/graceful restart apache with out reseting all of my users sessions and causing them to hit the SP again. On ajax based pages this is especially problematic. I realize everyone probably wouldn't want to do this but I feel a configurable options would be nice. 

Probably some kinda of dumping to disk either if there are hooks on restart/graceful or at set/approximate time intervals. I've started reading through the code but code use help understanding it and also thoughts on if this idea has any merit. If this is a stupid idea for some reason I would love to know what the issues with it are.

**Comment by olavmrk** [comment]
I think this is an issue that is better solved by adding some sort of alternative session backend. memcache has been mentioned a few times on the mailing list.

The advantage of that compared to adding disk saving on specific triggers / intervals to the current session backend is that it is simpler to implement while providing more functionality.

It is simpler in the way that in both cases a serialization format has to be implemented for loading and saving sessions, but in this case there would not have to be any logic for deciding when.

**Comment by ismailseyfi** [comment]
+1 for this. Any plans on when something like this may be available.

**Comment by rubelw** [comment]
Yes.  Having memcache or something similar is definately needed to prevent dumping of sessions after reload.

**Comment by gozer** [comment]
Why not just plug into Apache's socache ? https://httpd.apache.org/docs/trunk/socache.html

**Comment by unikent-ms1** [comment]
Going for something outside Apache would allow sharing of session state across nodes as well as across Apache restarts.

**Comment by SeppBender** [comment]
Is there any progress on this matter? The integration with socache would be awesome.

**Comment by psa-jforestier** [comment]
Will be great if we have an Apache web farm if sessions are shared between Apache servers. I think it cloud be implemented by using socache (with memcached or Redis support).

**Comment by ebogaard** [comment]
At this moment, any session back-end would be great. Be it a simple file-based something, a database or a separate persistent application.
SimpleSAMLphp, for example, has several options: https://simplesamlphp.org/docs/stable/simplesamlphp-maintenance#section_2

**Comment by stevecrozz** [comment]
It would be interesting to explore something like JWT so that the only shared resource between apache instances would be a secret signing key. This would allow any instance to read and trust sessions without a secondary storage mechanism.

**Comment by olavmrk** [comment]
Closing this issue as part of [archiving](https://help.github.com/en/articles/about-archiving-repositories) this project. See the announcement for details:

https://github.com/Uninett/mod_auth_mellon/blob/info/README.md
