### ISSUE TITLE
Configure error in line 3126: PKG_CHECK_MODULES(LASSO, lasso)

### ISSUE THREAD

**Issue by folkenfanel** [UNINETT/mod_auth_mellon#96]
I'm trying to setup mod_auth_mellon in Centos 5. Apache 2 is installed in /usr/local/apache2 and Openssl and Lasso .pc files are in /usr/lib64/pkgconfig.

Installed packages:
lasso and lasso-devel version 2.5.0, openssl 1.0.1e, Apache HTTPD 2.4.6;

I executed the commands above:
   export PKG_CONFIG_PATH=/usr/lib64/pkgconfig
   ./configure --with-apxs2=/usr/local/apache2/bin/apxs

The verbose was:

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... -std=gnu99
./configure: line 3126: syntax error near unexpected token `LASSO,'
./configure: line 3126: `PKG_CHECK_MODULES(LASSO, lasso)'

It's a bug? I'm missing something?

**Comment by olavmrk** [comment]
My guess is that you are missing [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/). Try to run something like to verify that pkg-config is working:
```
PKG_CONFIG_PATH=/usr/lib64/pkgconfig pkg-config lasso --libs
```

**Comment by folkenfanel** [comment]
The command line:
`PKG_CONFIG_PATH=/usr/lib64/pkgconfig pkg-config lasso --libs`

Printed:
`-llasso`

Got no problem with the version 0.7.0.

**Comment by vittala** [comment]
You'll get this error on CentOS if you don't run aclocal before running autoconf. The install process should be:

``> aclocal``
``> autoconf``
``> ./configure``

Seems to work for me on CentOS 6

Cheers
Vittal

**Comment by Garfius** [comment]
> You'll get this error on CentOS if you don't run aclocal before running autoconf. The install process should be:
> 
> `> aclocal`
> `> autoconf`
> `> ./configure`
> 
> Seems to work for me on CentOS 6
> 
> Cheers
> Vittal

This just takes you to next error:

configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `config.h.in'

Centos 6

**Comment by mautik** [comment]
Try
autoreconf
which runs autoconf, autoheader, aclocal, automake, libtoolize

**Comment by Garfius** [comment]
> Try
> autoreconf
> which runs autoconf, autoheader, aclocal, automake, libtoolize

Worked

Great, thanks!!
